kids-first/kf-ui-data-tracker

LICENSE
=> 📄 Add LICENSE file

src/components/Tokens/TokenList.js, src/views/TokensListView.js
- Change loading message
- Add copy-to-clipboard button for each token
Closes #147
=> ♻️ Refactor token view adding copy button

src/components/StudyList/StudyList.jsx, src/views/StudyFilesListView.js, src/views/StudyListView.js
File list on the loading stage:
Study list on the loading stage:
=> ♻️ Refactor loading state for study list and file list

package.json, yarn.lock
Adds `react-testing-library` to use for testing.
=> 📦 Add react-testing-library for testing

src/components/FileAnnotation/FileEditor.test.js, src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
Adds simple snapshot testing for the FileEditor component.
Will add some more detailed tests to the container component as part of the functional testing in #178.
Closes #162
=> 📷 Add snapshot tests for FileAnnotation

src/components/FileList/FileList.js, src/state/mutations.js
Rewrites the `studyByKfId` query to remove a file upon deletion. This prevents another request going to the server to fetch the file listing.
=> ♻️ Delete file from query cache

__mocks__/kf-api-study-creator/mocks.js, __mocks__/kf-api-study-creator/responses/allStudies.json, __mocks__/kf-api-study-creator/responses/deleteFile.json, __mocks__/kf-api-study-creator/responses/studyByKfId.json, package.json, src/views/StudyFilesListView.test.js, yarn.lock
Tests that the deletion of files results in the file being removed from the study's file listing.
Closes #179 
Merge #210 first to avoid having two different responses from the `studyByKfId` query.
=> ✅ Test file deletion from FileList

src/components/StudyList/__tests__/StudyList.test.js, src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap, src/components/StudyList/__tests__/allStudies.json
Adds a snapshot test for the `StudyList` component.
Closes #168
=> 📷 Add snapshot tests for StudyList

src/components/StudyHeader/StudyHeader.test.js, src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
Add snapshot tests for the StudyHeader component.
Closes #167
=> 📷 Add snapshot tests for StudyHeader

src/components/FileUpload/FileUploadTarget.test.js, src/components/FileUpload/__snapshots__/FileUploadTarget.test.js.snap
Adds snapshot tests for the upload box. Will add some more functional tests for the container in #178.
Closes #164
=> 📷 Add snapshot tests for FileUploadTarget

src/components/FileList/FileElement.js, src/components/FileList/__tests__/FileElement.test.js, src/components/FileList/__tests__/FileList.test.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/FileList/__tests__/studyByKfId.json
Adds snapshot testing for the `FileList` and `FileElement` components.
Closes #163
=> 📷 Add snapshot tests for FileList components

src/components/FileList/__tests__/FileElement.test.js, src/components/FileList/__tests__/FileList.test.js
Refactor snapshot test data mock so that the date would not change as the current date when snapshot tests are created.
=> ♻️ Refactor snapshot test data mock

CHANGELOG.md, package.json
Feature Emojis: ♻️x11 📷x6 ⬆️x2 🐛x1 ✅x1 🤡x1 📦x1 🔧x1 📄x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x22 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x4 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x4 [devops](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/devops) x1 [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x1 [documentation](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/documentation) x1
- (#215) ♻️ Refactor studies list - @bdolly
- (#225) ♻️ Implement SecondaryNav component to navbar - @XuTheBunny
- (#221) ♻️ Refactor copy button - @XuTheBunny
- (#223) ♻️ Refactor snapshot test …
=> 🏷 Release 0.2.0

__mocks__/kf-api-study-creator/mocks.js, src/common/fileUtils.js, src/components/Badge/Badge.js, src/components/Badge/badge.css, src/components/FileActionButtons/FileActionButtons.css, src/components/FileActionButtons/FileActionButtons.jsx, src/components/FileList/FileActions.jsx, src/components/FileList/FileElement.js, src/components/FileList/FileList.js, src/components/FileList/__tests__/FileElement.test.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/FileList/filelist.css, src/containers/FileActionsContainer.jsx, src/views/StudyFilesListView.js, src/views/__tests__/StudyFilesListView.test.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Restructures the Single Study File List and adds truncated file descriptions to list items
Closes #169
=> ♻️ Study File List improvements

src/common/fileUtils.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Changed string comparison to date comparison to make sorting not depend on locale
=> 🐛 Update date compare function

__mocks__/kf-api-study-creator/responses/fileByKfId.json, src/Routes/index.js, src/common/fileUtils.js, src/components/FileActionButtons/FileActionButtons.jsx, src/components/FileDetail/FileDetail.js, src/components/FileDetail/VersionItem.js, src/components/FileDetail/VersionList.js, src/components/FileDetail/__tests__/VersionItem.test.js, src/components/FileDetail/__tests__/VersionList.test.js, src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap, src/components/FileDetail/__tests__/fileByKfId.json, src/components/FileDetail/file-detail.css, src/components/FileList/FileElement.js, src/components/NavBar/NavBar.js, src/containers/DeleteFileMutation.js, src/containers/FileActionsContainer.jsx, src/containers/FileDetailContainer.js, src/containers/FileEditorContainer.js, src/containers/UploadContainer.js, src/state/mutations.js, src/state/queries.js, src/views/FileDetailView.js, src/views/__tests__/FileUpload.test.js, src/views/index.js
=> ✨ Add file detail view

.circleci/config.yml, package.json
Adds bundlesize CI status check to keep our bundle size in check.
=> 👷 Add bundlesize status check

__setups__/icons.js, src/assets/icons/edit.js, src/assets/icons/notification.js, src/components/FileDetail/NotificationBar.js, src/components/FileDetail/file-detail.css
Notification bar would be used inside file detail modal
Displays notification bar with one main button (current)
To preview the component, go to /component_preview
Preview commit would be removed before merging
=> ✨ Add notification bar component

package.json, src/components/Modal/Modal.js, src/components/Modal/ModalFooter.js, src/components/Modal/ModalHeader.js, src/components/Modal/__tests__/Modal.test.js, src/components/Modal/__tests__/__snapshots__/Modal.test.js.snap, src/components/Modal/modal.css, yarn.lock
Modal component is using ReactModal as a base including build-in header and footer.
To preview the component, go to /component_preview
Preview commit would be removed before merging
=> ✨ Add modal component

__mocks__/kf-api-study-creator/responses/fileByKfId.json, __mocks__/kf-api-study-creator/responses/updateFile.json, src/components/FileAnnotation/FileEditor.js, src/components/FileAnnotation/FileEditor.test.js, src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap, src/containers/FileEditorContainer.js, src/containers/UploadContainer.js, src/state/queries.js, src/views/AnnotationView.js, src/views/StudyFilesListView.js
- The editor container and the upload container only contain queries and mutations.
- The upload container needs to adapt to the new requirement for uploading a new version of a file.
- The editor container needs to rewrite local cache instead of refetch query when change happens.
- The editor markup needs to adapt to the design for annotation modal on the file detail page.
=> ♻️ Refactor editor and upload container

src/components/FileAnnotation/FileEditor.js, src/components/FileDetail/AnnotateVersionModalContainer.js, src/components/FileDetail/FileDetail.js, src/components/FileDetail/FileDetailModal.js, src/components/FileDetail/UploadVersionModalContainer.js, src/components/FileDetail/VersionList.js, src/components/FileDetail/__tests__/EditExistingFile.test.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap, src/components/FileDetail/file-detail.css
Closes #177
Closes #243 
Closes #241
=> ✨ Add modal view for version upload and annotation

package.json, src/components/FileList/FileList.js, src/components/FileList/__tests__/FileList.test.js, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/FileList/__tests__/studyByKfId.json, src/components/FileList/filelist.css, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap, yarn.lock
=> ✨ Add pagination on file list 

src/Routes/index.js
Logs a user out by deleting tokens and refreshing the page.
Fixes #227
=> ✨ Add logout button

CHANGELOG.md, package.json
Introduce new version uploading functionality.
Feature Emojis: ✨x7 ♻️x3 💄Refactorx2 💄x2 🐛x2 ✅x2 👷x1 🚑x1 🔥 x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x9 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x6 [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x4 [component](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/component) x4 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x4 [devops](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/devops) x1 [ready-for-review](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/ready-for-review) x1
- (#262) ✨ Add logout button - @dankolbman
- …
=> 🏷 Release 0.3.0

src/components/FileDetail/FileDetail.js, src/components/FileDetail/FileDetailModal.js, src/modals/NewVersionModal/DescriptionStep.js, src/modals/NewVersionModal/NewVersionFlow.js, src/modals/NewVersionModal/UploadStep.js, src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js, src/modals/index.js, src/state/mutations.js
Adds a multistep flow within a modal to choose a file and enter a change summary.
TODO: Refactor modals some more.
Closes #268
=> ✨ Add new version flow

__mocks__/kf-api-study-creator/responses/fileByKfId.json, __mocks__/kf-api-study-creator/responses/studyByKfId.json, src/common/fileUtils.js, src/components/Badge/Badge.js, src/components/Badge/__tests__/Badge.test.js, src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap, src/components/Badge/badge.css, src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap, src/components/FileDetail/FileDetail.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/FileElement.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/state/queries.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Badge component is updated on the file list and file detail view.
Closes #277
=> ♻️ Refactor badge component taking version state data

__mocks__/kf-api-study-creator/responses/fileByKfId.json, __mocks__/kf-api-study-creator/responses/studyByKfId.json, src/components/FileDetail/FileDetail.js, src/components/FileDetail/VersionItem.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap, src/components/FileList/__tests__/studyByKfId.json, src/state/queries.js
Avatar component is updated on the file detail view and version list.
Closes #278
=> ♻️ Refactor avatar component taking creator data

src/App.css, src/Routes/index.js, src/forms/UpdateProfileForm.js, src/state/mutations.js, src/state/queries.js, src/views/ProfileView.js, src/views/index.js
Provides a page where the user can see their profile details and change
data tracker specific settings.
*Wait for myProfile and additional fields from the API*
=> ✨ Add user profile page

src/components/StudyList/StudyTable.js, src/containers/StudySubscriptionContainer.js, src/state/mutations.js, src/state/queries.js, src/views/ProfileView.js
Adds a study subscription manager so that users may view all studies available for subscription and manage their subscriptions.
=> ✨ Study subscriptions manager

src/components/FileDetail/FileDetail.js, src/components/FileDetail/FileDetailModal.js, src/components/Modal/Modal.js, src/components/Modal/ModalFooter.js, src/components/Modal/modal.css, src/components/VersionList/VersionItem.js, src/components/VersionList/VersionList.js, src/modals/NewVersionModal/NewVersionFlow.js, src/modals/VersionInfoModal/VersionInfoModal.js, src/modals/index.js
=> ✨ Add version detail modal

CHANGELOG.md, package.json
Flow refactoring and notification settings.
Feature Emojis: ♻️x5 ✨x4 🐛x1 🚚 x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x8 [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x5 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x4 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x1
- (#285) ♻️  Refactor document edit modal - @XuTheBunny
- (#284) ✨ Add version detail modal - @XuTheBunny
- (#283) ✨ Study subscriptions manager - @dankolbman
- (#282) ♻️  Refactor version upload and annotation modal style - @XuTheBunny
- (#281) ♻️  Refactor version list component - @XuTheBunny
- (#274) ✨ Add user profile page - @dankolbman
- (#280) ♻️ …
=> 🏷 Release 0.4.0

__mocks__/kf-api-study-creator/mocks.js, __mocks__/kf-api-study-creator/responses/updateVersion.json, src/common/fileUtils.js, src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap, src/components/FileDetail/__tests__/EditExistingFile.test.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/forms/EditDocumentForm.js, src/modals/EditDocumentModal.js, src/state/mutations.js
=> ✨ Add approval status dropdown to file annotation modal

src/Routes/index.js, src/components/HeaderButton/HeaderButton.js
=> ✨ Add profile dropdown to header

src/forms/NewDocumentForm.js, src/modals/NewVersionModal/NewVersionFlow.js, src/views/NewDocumentView.js
Set the "UPLOAD" button to be disabled and showing "UPLOADING"
Upload new file:
Upload new version:
Closes #295
=>  ✨ Add "uploading" stage to submit button when uploading new file or new version

src/Routes/PrivateRoute.js, src/components/Login/Login.js, src/state/auth.js, src/views/LoginView.js
When a user enters the data tracker through some non-root url, but they are not authenticated yet, they should be sent through authentication and returned to their originally requested page.
Closes #276
=> ✨ Redirect user back to the original requested page after login

src/common/fileUtils.js
=> 🐛 Fix file type icon mismatch

src/components/FileDetail/file-detail.css, src/components/FileList/__tests__/FileList.test.js, src/components/Modal/modal.css, src/modals/NewVersionModal/NewVersionFlow.js, src/modals/NewVersionModal/UploadStep.js, src/modals/VersionInfoModal.js
removes the use of `Modal--<size>` classes for specific modals in favor of using 
```css
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```
reference: https://css-tricks.com/centering-css-complete-guide/
--- 
also adds some minor styling tweaks to various modals
=> 💄 refactor modal positioning

src/App.css, src/components/StudyList/StudyTable.js, src/forms/UpdateProfileForm.js, src/views/ProfileView.js
For user has no groups:
For user has groups:
=> 💄 Profile view bug fix and style updates

src/common/fileUtils.js, src/components/Badge/Badge.js, src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap, src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
File detail:
File list:
File edit:
=> 💄 Use semantic for badges

src/forms/UpdateProfileForm.js, src/views/ProfileView.js
Replace profile view with Semantic UI.
=> 💄 Use Semantic for Profile View

src/App.css, src/components/AvatarTimeAgo/AvatarTimeAgo.js, src/components/AvatarTimeAgo/__tests__/AvatarTimeAgo.test.js, src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap, src/components/FileAnnotation/SelectElement.js, src/components/FileDetail/FileDetail.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/VersionList/VersionItem.js, src/components/VersionList/VersionList.js, src/components/VersionList/_tests_/VersionItem.test.js, src/components/VersionList/_tests_/VersionList.test.js, src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap, src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap, src/containers/FileDetailContainer.js, src/forms/__snapshots__/NewDocumentForm.test.js.snap, src/modals/VersionInfoModal.js, src/views/FileDetailView.js
Use [semantic components](https://react.semantic-ui.com/) to replace all the uikit components and some of the local components.
Before:
After:
Semantic components used:
- Icon
- Header
- Button
- Label
- Grid
- Segment
- List
Closes #303
=> 💄 Use Semantic for File Detail view

src/components/VersionList/VersionItem.js
Makes clicking anywhere on the version item launch the version modal.
=> ♻️ Make entire version item row clickable

src/components/FileDetail/FileDetail.js, src/components/FileList/__tests__/FileElement.test.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/forms/NewDocumentForm.js, src/modals/NewVersionModal/DescriptionStep.js
Solves some of the issues with incorrect html that were throwing errors both in tests and the console.
Unfortunately, we cannot easily solve the `act()` warnings, but a fix is in react's master and should fix itself once version 16.9.0 is released.
Fixes #334
=> 🐛 Handle test errors

src/components/FileUpload/FileUploadTarget.js, src/components/FileUpload/FileUploadTarget.test.js, src/components/FileUpload/__snapshots__/FileUploadTarget.test.js.snap, src/containers/FileDetailContainer.js, src/modals/NewVersionModal/NewVersionFlow.js, src/views/NavBarView.js, src/views/ProfileView.js, src/views/StudyFilesListView.js, src/views/StudyListView.js, src/views/TokensListView.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
- Study list view
- Token view
- File list view
- Profile view
- NavBar view
- VersionUpload modal
- File detail view
- File upload target
Closes #310
=> 💄 Use Semantic for error message

src/components/FileList/FileList.js, src/components/FileList/__tests__/FileList.test.js, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/FileList/__tests__/studyByKfId.json, src/components/StudyList/StudyList.js, src/containers/StudySubscriptionContainer.js, src/forms/NewTokenForm.js, src/forms/UpdateProfileForm.js, src/modals/VersionInfoModal.js
♻️ Change file list pagination to be 10 files per page
📷 Update test for file list pagination
Closes #361
♻️ Remove createdAt and modifiedAt columns from study list
Closes #370 
🐛 Fix token name input field focus prop value
Closes #373
=> 💄 Semantic refactor for study list and file list

src/App.css, src/common/fileUtils.js, src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap, src/components/FileDetail/FileDetail.js, src/components/FileDetail/__tests__/EditExistingFile.test.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/VersionList/VersionItem.js, src/components/VersionList/VersionList.js, src/components/VersionList/_tests_/VersionItem.test.js, src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap, src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap, src/forms/__snapshots__/EditDocumentForm.test.js.snap, src/modals/NewVersionModal/DescriptionStep.js, src/modals/VersionInfoModal.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
=> 💄 Semantic refactor version list and file detail view

src/views/EmptyView.js
=> 💄Use semantic for empty stage view

src/state/fragments.js, src/state/mutations.js, src/state/queries.js, src/views/TokensListView.js
This adds a token fragment to ensure that tokens are retrieved with the same fields consistently to prevent refetches.
closes #364
=> ♻️ Add Token fragment

src/views/NavBarView.js
This replaces the `<Query />` component with a `graphql` HOC to be more consistent across views.
Closes #358
=> ♻️ Replace Query component with HOC in navbar

src/views/StudyListView.js
This replaces the `<Query />` component with a `graphql` HOC to be more consistent across views.
Closes #359
=> ♻️ Replace Query component with HOC in study list

src/App.css, src/common/fileUtils.js, src/components/Badge/Badge.js, src/components/FileList/FileElement.js, src/components/FileList/FileList.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/VersionList/VersionItem.js, src/containers/FileDetailContainer.js, src/modals/NewVersionModal/DescriptionStep.js, src/modals/VersionInfoModal.js, src/views/NewDocumentView.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Before sorting:
After sorting:
Emphasizing "Changes Needed" status:
Closes #383
=> 💄 Study File List sort status of changes needed to the top

CHANGELOG.md, package.json
Replace ui kit with Semantic. General code improvements.
Feature Emojis: 💄x5 ♻️x5 ✨x4 🐛x2 🔥 x1 x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x9 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x7 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x3 [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x3 [component](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/component) x2
- (#385) 💄 Study File List sort status of changes needed to the top - @XuTheBunny
- (#369) ♻️  Replace Query component with HOC in study file list - @dankolbman
- (#371) ♻️  Replace Query component with HOC in study list - @dankolbman
- (#372) ♻️ …
=> 🏷 Release 0.5.0

__mocks__/kf-api-study-creator/responses/studyByKfId.json, __mocks__/kf-api-study-creator/responses/updateFile.json, src/components/FileList/__tests__/studyByKfId.json, src/state/fragments.js, src/state/mutations.js, src/state/queries.js
Define fragments for study field, file fields, version fields, and creator fields to prevent unnecessary refetches.
Closes #368 
Closes #365 
Closes #366 
Closes #367
=> ♻️ Fragments for study field, file fields, version fields, and creator fields

README.md
Add:
- Development Quick Start
- Testing
Closes #247
=> 📝 Update README file with development and testing section

src/App.css, src/common/fileUtils.js, src/components/FileDetail/__tests__/EditExistingFile.test.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/FileElement.js, src/components/FileList/FileList.js, src/components/FileList/__tests__/FileList.test.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/FileList/__tests__/studyByKfId.json, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Default:
Filter by approval status:
Filter by file type:
Sort by date:
Seach:
Combo:
Closes #103 
Closes #180
Closes #181
=> ✨ Filter files by approval status/type, sort by created/modified date, and search by file title/description

src/App.css, src/components/StudyList/StudyList.js, src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap, src/components/ToggleButtons/ToggleButtons.js, src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
=> ✨ Search study by its name / short name from study list screen

src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/Header/Header.js
Show alternative image when no user profile photo exist
Add alt text for the image as user name or 'profile' as default
Before:
After:
Closes #404
=> 💄 Show alternative image when no user profile photo exist

src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/Header/Header.js
Adds a dropdown menu that is only visible to admins that offers navigation to administrative pages.
=> ✨ Add drop down for admin functions

package.json, src/Routes/index.js, src/components/StudyList/StudyList.js, src/components/StudyList/__tests__/StudyList.test.js, src/forms/NewStudyForm.js, src/state/fragments.js, src/state/mutations.js, src/state/queries.js, src/views/NewStudyView.js, src/views/index.js, yarn.lock
=> ✨ Add form page for creating new study

src/components/CavaticaProjectList/CavaticaProjectList.js, src/views/CavaticaProjectsView.js
Shows an indicator next to a project that has been deleted.
Reports number of projects that were deleted as the result of a sync.
Hides workflow type for non-delivery projects.
=> ✨ Show information about deleted projects

src/forms/EditDocumentForm.js, src/views/NewDocumentView.js
From NewDocumentView get user data, check if the user is ADMIN, and pass a boolean value to file annotation form as a prop.
=> 🐛 Fix new file annotation form by adding user object to it

src/common/enums.js, src/components/StudyInfo/StudyInfo.js, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, src/forms/NewProjectForm.js, src/forms/index.js, src/modals/NewProjectModal.js, src/state/mutations.js, src/views/StudyInfoView.js
Adds a modal form in the study info page to create a new analysis project in Cavatica.
Closes #417
=> ✨ Add form for new Cavatica project

CHANGELOG.md, package.json
Adds views for creating studies and projects.
Feature Emojis: ✨x10 🐛x4 💄x3 🔥x1 📝x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x10 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x8 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x4 [component](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/component) x4 [devops](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/devops) x2 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x1 [documentation](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/documentation) x1
- (#428) 🔥 Move role and group resolvers to server - @dankolbman
- (#426) ✨ …
=> 🏷 Release 0.6.0

.env.schema, README.md
Updates the default API url and clearifies the README.
=> 🔧 Update env schema

src/components/CavaticaProjectList/CavaticaProjectItem.js, src/components/CavaticaProjectList/CavaticaProjectList.js, src/state/mutations.js, src/views/CavaticaProjectsView.js
=> ♻️ Refactor project list showing unlink button for admin user

src/App.css, src/components/StudyInfo/StudyInfo.js, src/components/StudyInfo/__tests__/StudyInfo.test.js, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, src/forms/LinkProjectForm.js, src/forms/index.js, src/modals/LinkProjectModal.js, src/state/queries.js, src/views/StudyInfoView.js
=> ✨ Add modal for link / unlink Cavatica project

src/Routes/index.js, src/components/EventList/index.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/Header/Header.js, src/state/queries.js, src/views/EventsView.js, src/views/index.js
Adds an administrative view to allow admins to view event history, sortable by username, study, and event type.
=> ✨ Add view for event history

src/common/enums.js, src/forms/NewStudyForm.js, src/state/mutations.js, src/views/NewStudyView.js
=> ✨ Add option to create which type of Cavatica projects on creating a new study

src/components/StudyInfo/StudyInfo.js, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, src/views/StudyInfoView.js
=> 💄 Refactor study info layout

src/forms/EditStudyForm.js, src/forms/NewProjectForm.js, src/forms/NewStudyForm.js, src/modals/EditStudyModal.js
Add version, attribution and bucket field to edit study form:
Closes #440
=> 💄 Refactor study edit layout and add more fields

package.json, src/App.css, src/components/StudyInfo/StudyInfo.js, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, yarn.lock
=> ✨ Support markdown for study description

src/App.css, src/modals/EditStudyModal.js
=> 💄 Display api error message at the bottom of the edit study modal

src/App.css, src/components/CavaticaProjectList/CavaticaProjectItem.js, src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap, src/components/StudyInfo/StudyInfo.js, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, src/forms/NewStudyForm.js, src/modals/NewProjectModal.js
- Ensure error message are handled and passing valid props (on success case and error case)
- Ensure the page data (cache) are updated after mutation
- Emphasize less on the deleted projects 
- Hide redundant info for clear appearance 
Cavatica Project card on Study Basic Info page:
Before:
After:
Cavatica Projects page:
Before:
After:
=> ♻️ Refactor create project and list project rendering

CHANGELOG.md, package.json
New BIX features for Cavatica projects, UI refactoring and fixes.
Feature Emojis: ✨x7 ♻️x4 💄x3 🐛x2 🔧x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x9 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x6 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x4 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x2 [usability improvement](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/usability%20improvement) x1 [devops](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/devops) x1 [documentation](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/documentation) x1
- (#476) 🐛 Allow selection of …
=> 🏷 Release 0.7.0

src/App.css, src/Routes/index.js, src/components/StudyList/StudyList.js, src/forms/EditStudyForm.js, src/forms/FormField.js, src/forms/NewStudyForm.js, src/forms/StudyFormSteps.js, src/modals/EditStudyModal.js, src/views/NewStudyView.js
- Use three steps for creating a study
- Adjust the alignment of the input box and field description to have a cleaner look
- Fix minor bug on edit study modal submit button
New study form:
Before:
After:
Edit study modal:
Before:
After:
Closes #455
=> 💄 Re-style input hints for study form

src/common/enums.js, src/components/CavaticaProjectList/CavaticaProjectItem.js, src/components/CavaticaProjectList/CavaticaProjectList.js, src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap, src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap, src/forms/EditProjectForm.js, src/forms/LinkProjectForm.js, src/forms/index.js, src/modals/EditProjectModal.js, src/modals/index.js, src/state/mutations.js, src/views/CavaticaProjectsView.js
Adds a modal to edit existing Cavatica projects' workflow and project type.
Closes #464
=> ✨ Edit Project modal

public/index.html
adds the UserSnap widget to the bottom right hand corner
=> ✨ Feature UserSnap widget 

src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/FileElement.js, src/components/FileList/FileList.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/views/StudyFilesListView.js, src/views/__tests__/StudyFilesListView.test.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Design improvement based on usability testing feedback:
- re-order attributes in order of importance 
- remove unused document `kfId` copy button 
- normalize color and weight of attributes text
- reduce size of upload document target 
- add table headers to file list 
- add version count to attributes
**BEFORE**
**AFTER**
**
=> 💄Re-style Study  List Item attributes 

src/App.css, src/common/fileUtils.js, src/components/Badge/Badge.js, src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/FileElement.js, src/components/FileList/FileList.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/ListFilterBar/ListFilterBar.js, src/modals/UploadWizard/UploadWizard.js, src/modals/UploadWizard/__tests__/UploadWizard.test.js, src/views/StudyFilesListView.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
This uses a temporary sessionStorage value to trigger highlighting of file rows that have been updated with a new version from the UploadWizard. Highlighting is removed after 7sencods and the sessionStorage value is cleared 
Closes #400
=> ✨Updated Document Indicator

src/state/mutations.js, src/state/queries.js
Fix `Error writing result to store for query` by adding query name to allStudies query.
Closes #475
=> 🐛 Add query name to solve Error writing result to store for query

__mocks__/kf-api-study-creator/responses/studyByKfId.json, src/components/CopyButton/CopyButton.js, src/components/CopyButton/__snapshots__/CopyButton.test.js.snap, src/components/FileActionButtons/FileActionButtons.js, src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/components/FileList/FileElement.js, src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap, src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap, src/state/queries.js, src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
allow users to copy a download link the to most recent version of a document  #393
This copies `<download_url>/download/study/<study_id>/documents/<doc_id>/version/<version_id>` to the users clipboard
Closes #472
=> ✨FileElement copy download link action button

CHANGELOG.md, package.json
Adds required action alerts and various UX improvements.
Feature Emojis: ✨x10 💄x3 🐛x2 ♻️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x10 [usability improvement](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/usability%20improvement) x5 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x4 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x4 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x4
- (#484) ✨ FileElement copy download link action button - @bdolly
- (#496) 🐛 Add query name to solve Error writing result to store for query - @XuTheBunny
- (#495) ✨ Add alert for study data completeness to study info page - …
=> 🏷 Release 0.8.0

CHANGELOG.md, package.json
Hotfix for file downloads.
Feature Emojis: 📷x3 🐛x1
Feature Labels: [component](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/component) x3 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x3 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x1
- (#509) 🐛 Fix download mutation by removing the id - @XuTheBunny
- (#497) 📷 Improve Snapshot Coverage 3/3 - @XuTheBunny
- (#500) 📷 Improve Snapshot Coverage 2/3 - @XuTheBunny
- (#499) 📷 Improve Snapshot Coverage 1/3 - @XuTheBunny
=> 🏷 Release 0.8.1

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
---
> Default issue template for Feature Request/UX improvements:
---
Who is the intended audience impacted by this change? This should be a link to a pre-defined persona and not free text
What is the intention of this change? What outcome do you hope to see from this change?
- Detailed feature1 description
- Detailed feature2 description
UI changes should be supported by data and not guesses. What empirical evidence from the above persona do you have to support this change? (usability testing data, interviews, analytics data, a direct quotation from user feedback)
---
> Issue template for bug reports:
---
Provide the specific semantic version number of the UI (example: 1.7.0, 1.6.5, etc). This can be found in the package.json
Provide the specific page url where the issue was noticed …
=> 📝 Add pull request template

.circleci/config.yml, README.md, jest.config.js, package.json, yarn.lock
- Add Codecov test as default pull request checking method
No UI changes
| Safari (12)      |  ✖️   |   ✖️     |  ✖️      |    ✖️    |
=> ✅ Add Codecov test as default pull request checking method

.github/ISSUE_TEMPLATE/feature_request.md
Adding the requirements section into feature request issue template:
Wireframes, mockups or detailed of the feature to the implemented.
=> 📝 Update feature request issue template adding "requirements" section

CHANGELOG.md, package.json
Add hot jars
Feature Emojis: 📈x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x1 [documentation](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/documentation) x1
- (#557) 📈 Hotjar tracking script in head tag - @bdolly
=> 🏷 Release 0.9.1

CHANGELOG.md, package.json
Token fixes and new study creation status view.
Feature Emojis: ✨x2 🐛x1 🔥x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x2 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x1 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x1
- (#554) ✨ Add new study creation status view - @XuTheBunny
- (#561) 🐛 Allow admin user to copy newly created token - @XuTheBunny
- (#560) 🔥 Remove BETA user checking from study info page - @XuTheBunny
- (#553) ✨ Add page titles to all views - @XuTheBunny
=> 🏷 Release 0.10.0

__mocks__/kf-api-study-creator/mocks.js, __mocks__/kf-api-study-creator/responses/allEvents.json, __mocks__/kf-api-study-creator/responses/allEvents_20.json, __mocks__/kf-api-study-creator/responses/allEvents_40.json, __mocks__/kf-api-study-creator/responses/allEvents_refetch.json, __mocks__/kf-api-study-creator/responses/allEvents_studyCreation.json, __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_err.json, __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_ing.json, src/components/EventList/EventList.js, src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap, src/state/queries.js, src/views/EventsView.js, src/views/LogsView.js, src/views/__test__/EventsView.test.js, src/views/__test__/LogsView.test.js, src/views/__test__/__snapshots__/EventsView.test.js.snap, src/views/__test__/__snapshots__/LogsView.test.js.snap
- Update allEvents query to accept first and after input for pagination, and include cursor and pageInfo into the data
- Add "More" button on event page to fetch more (20 events more per click)
**[KF Data Tracker - Events](https://deploy-preview-576--kf-ui-data-tracker.netlify.com/events)**
First loaded: (20 events)
Clicked on More: (40 events)
**[KF Data Tracker - Study logs](https://deploy-preview-576--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/logs)**
| IE (_version_)      |        |       |       | …
=> ✨ Paginate events list

CHANGELOG.md, package.json
Add configuration view for admins
Feature Emojis: ✨x5 ♻️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x5 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x2
- (#538) ✨ Add Release coordinator status page under each study - @XuTheBunny
- (#574) ✨ Add configuration view - @dankolbman
- (#572) ✨ Add file import button - @dankolbman
- (#576) ✨ Paginate events list - @XuTheBunny
- (#570) ✨ Allow users to specify and name research projects on creation - @XuTheBunny
- (#573) ♻️ Sort deleted projects to bottom of list - @dankolbman
=> 🏷 Release 0.10.1

__mocks__/kf-api-study-creator/mocks.js, __mocks__/kf-api-study-creator/responses/fileByKfId_empty.json, __mocks__/kf-api-study-creator/responses/studyByKfId_empty.json, src/Routes/index.js, src/documents/views/FileDetailView.js, src/documents/views/StudyFilesListView.js, src/views/CavaticaBixView.js, src/views/LogsView.js, src/views/NotFoundView.js, src/views/ReleasesView.js, src/views/StudyInfoView.js, src/views/__tests__/NotFoundView.test.js, src/views/__tests__/__snapshots__/NotFoundView.test.js.snap, src/views/index.js
- Handle unknown study id and document id cases to avoid compile error
- Display customized 404 page for invalid url request with back to home page button
Closes #549
=> ✨ Add 404 page for invalid url

__mocks__/kf-api-study-creator/responses/status.json, src/admin/views/__tests__/__snapshots__/ConfigurationView.test.js.snap, src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap, src/state/queries.js
Adds settings to the configuration view for new study buckets settings.
**Page name here:**
**Before:**
`<ScreenShots>`
**After:**
`<ScreenShots>`
Closes #issue-number
=> ♻️ Add settings

src/state/mutations.js
Updates the mutation type as was changed in kids-first/kf-api-study-creator#353
=> ♻️ Update create study type name

CHANGELOG.md, package.json
Adds document tagging and administrative views.
Feature Emojis: ✨x8 ♻️x5 🔥x1 🐛x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x8 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x6 [usability improvement](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/usability%20improvement) x1
- (#612) ♻️ Update create study type name - @dankolbman
- (#613) 🔥 Remove research studies - @dankolbman
- (#603) ✨ Add editable document tags in document list and document detail - @XuTheBunny
- (#609) ✨ Add buckets view - @dankolbman
- (#610) 🐛 Fixing redirect typo - @abgeorge7
- (#599) ✨ Add users view for admin - @XuTheBunny
- (#596) ♻️ Add settings - @dankolbman
- (#593) ✨ Add create new research …
=> 🏷 Release 0.11.0

CHANGELOG.md, package.json
Hot fix for document upload regression.
Feature Emojis: 🐛x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x1
- (#615) 🐛 Fix new document creation by adding empty tag list - @XuTheBunny
=> 🏷 Release 0.11.1

src/Routes/TrackedRoute.js, src/Routes/index.js
Adds relevant analytics scopes to views and triggers events on render.
=> 📈 Add scope and events to page views

src/documents/components/FileDetail/FileDetail.js
💄 Displaying user who made the last changes on the file
**File detail page:**
**Before:**
**After:**
Closes #624
=> 💄 Displaying user who made the last changes on the file

src/common/enums.js, src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap, src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap, src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap, src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap, src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap, src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
✨ Add DBG file type for dbGaP Submission File
Closes #602
=> ✨ Add DBG file type for dbGaP Submission File

.github/ISSUE_TEMPLATE/bug_report.md
Updates the issue template for bug reports to make it more concise.
=> 📝 Update the bug template for issues

netlify.toml, src/common/globals.js, src/state/auth.js
Logs users out from Auth0 so that they are re-prompted with the Auth0 login screen the next time they try to login rather than restoring their previous session.
Fixes #644
=> 🐛 Log users out of Auth0

src/common/__tests__/permissions.test.js, src/common/permissions.js, src/components/Header/Header.js
Only shows admin dropdown if the user has permissions for one or more of the items.
Only shows items that the user has permissions for.
Fixes #641
=> ♻️ Check permissions for admin dropdown

src/common/enums.js, src/documents/components/FileDetail/FileTags.js, src/documents/views/StudyFilesListView.js
♻️ Disable add tag button when no option selected
♻️ Auto focus tag dropdown when open 
♻️ Add Data Dictionary into default file tag options
♻️ Change tag to <a> tag component to have hover stage
♻️ Sort files by the create date for its latest version by default
**File list page:**
Closes #623
Closes #642
=> ♻️ Auto focus add tag dropdown input on open

.circleci/config.yml, cypress/integration/navigation/admin_navigation.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, jest.config.js, package.json, src/components/Header/Header.js, yarn.lock
Combines coverage results for integration and unit tests to report to codecov to give an overall report of the test coverage of the codebase.
closes #635
=> ✅ Add test coverage for integration tests

.circleci/config.yml, cypress/integration/navigation/admin_navigation.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, jest.config.js, package.json, src/components/Header/Header.js, yarn.lock
- Detailed feature1 implemented in this pull request
- Detailed feature2 implemented in this pull request
**Page name here:**
**Before:**
`<ScreenShots>`
**After:**
`<ScreenShots>`
Closes #issue-number
=> User groups tests

.github/pull_request_template.md
Simplifies the pull request template and expands the comments for the sections.
=> 📝 Update PR template

src/routes/index.js
Protects users admin view by checking that the user have the `view_user` permission.
Closes #653
=> 🔒 Protect users view

src/routes/index.js
Checks that user has the `view_bucket` and `list_all_bucket` permissions for the bucket admin page.
Closes #655
=> 🔒 Protect buckets

src/routes/index.js
Checks that the user have the `view_downloadtoken` permission for the token view.
Closes #656
=> 🔒 Protect tokens

.gitignore
Updates the `.gitignore` file with coverage and test artifacts.
=> 🙈  Update .gitignore with test files

src/App.js, src/common/globals.js, src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap, src/components/Header/DevHeader.js, src/components/Header/Header.js, src/state/queries.js
Adds a developer toolbar when either the settings are found to contain `developmentEndpoints = true` or `REACT_APP_DEV_BAR=true` in the environment.
Adds buttons to trigger development endpoints which will only be available in local environments to assist with development and testing.
=> ✨ Add developer toolbar

.circleci/config.yml, cypress.json, cypress/integration/navigation/admin_navigation.spec.js, cypress/integration/navigation/user_navigation.spec.js, cypress/integration/studies/add_study.spec.js, cypress/integration/studies/study_list.spec.js, cypress/support/commands.js, docker-compose.yml, src/routes/index.js
Adds commands to reset the database and change the test user's permission groups on the backend.
=> ✅ Test different user groups

cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js
✅ Adjust document list test based on mock data
✅ Add test for document detail page with edit permission
=> ✅ Adjust document list test based on mock data

.circleci/config.yml, docker-compose.yml
Adds coordinator to the docker compose and runs it in the circle tests.
=> 🐛 Add coordinator to compose

cypress/integration/studyInfo/release.spec.js, docker-compose.yml
Correctly set the address for the release coordinator in the docker compose.
=> 🐛 Use correct address for coordinator

.circleci/config.yml, cypress/integration/studyInfo/basic_info.spec.js, cypress/integration/studyInfo/cavatica.spec.js, cypress/integration/studyInfo/collaborators.spec.js, cypress/integration/studyInfo/logs.spec.js, cypress/integration/studyInfo/release.spec.js, docker-compose.yml, src/common/notificationUtils.js, src/components/CavaticaProjectList/CavaticaProjectItem.js, src/components/CavaticaProjectList/CavaticaProjectList.js, src/components/CavaticaProjectList/StudyProjects.js, src/components/EventList/EventList.js, src/components/Header/DevHeader.js, src/components/StudyList/ColumnSelector.js, src/forms/AddCollaboratorForm.js, src/forms/FormField.js, src/forms/StudyInfoForm/NewStudyForm.js, src/forms/StudyInfoForm/Steps/ExternalStep.js, src/forms/StudyInfoForm/Steps/InfoStep.js, src/forms/StudyInfoForm/Steps/LogisticsStep.js, src/modals/EditProjectModal.js, src/modals/LinkProjectModal.js, src/views/CavaticaBixView.js, src/views/LogsView.js, src/views/NavBarView.js, src/views/ReleasesView.js, src/views/StudyInfoView.js
Show/hide components on study `Basic Info`, `Cavatica`, `Collabrators`, `Logs`, and `Release (BETA)` tab.
Fixed minor errors.
Add tests for each tab.
=> 🔒 Check for permissions on study related tabs

CHANGELOG.md, package.json
Overhaul user permissions and redesign the study listing page for users.
Feature Emojis: 🔒x10 ✨x9 🐛x5 ✅x4 ♻️x3 📝x2 🎨x1 🙈x1 💄x1 📈x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x20 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x7 [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x7 [devops](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/devops) x6 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x2 [documentation](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/documentation) x1
- (#680) 🔒 Check for permissions on study related tabs - @XuTheBunny
- (#688) 🐛 Use correct address for coordinator - …
=> 🏷 Release 0.12.0

cypress/integration/studies/study_list.spec.js, src/components/StudyList/StudyList.js
Adds a toggle button to the Study List view to allow the table to made the full width of the browser and back.
Closes #695
=> ✨ Full width study table toggle

.circleci/config.yml, cypress/integration/studies/study_statuses.spec.js, src/common/__tests__/sortUtils.test.js, src/common/sortUtils.js, src/components/StudyList/StudyTable.js
Correctly sorts semantic version numbers.
Fixes #693
=> 🐛 Fix version sorting

cypress/integration/documents/document_detail.spec.js, cypress/integration/studies/study_statuses.spec.js, src/components/StudyList/IngestionStatus.js, src/components/StudyList/PhenotypeStatus.js, src/components/StudyList/StudyList.js, src/components/StudyList/StudyTable.js, src/state/fragments.js, src/state/mutations.js
Add ingestion status and phenotype status to study table
Closes #690 
Closes #691
=> ✨ Add ingestion status and phenotype status to study table

cypress/integration/studies/study_list.spec.js, src/components/StudyList/StudyList.js, src/components/StudyList/StudyTable.js, src/components/StudyList/__tests__/StudyTable.test.js, src/containers/StudySubscriptionContainer.js
Save study table sorting state to local storage (`sortingColumn` and `sortingDirection`)
Closes #694
=> ✨ Persist study list column sort state

src/components/AvatarTimeAgo/AvatarTimeAgo.js, src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap, src/documents/components/FileList/FileElement.js, src/state/fragments.js
✨ Add user name as hover stage to user avatar component
✨ Add document type name and description as hover stage to type icon
Closes #703
=> ✨ Add hover state to component with descriptive information

CHANGELOG.md, package.json
Small UX improvements based on feedback.
Feature Emojis: ✨x3 🔥x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/refactor) x3 [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x2
- (#707) ✨ Display collaborators full name - @XuTheBunny
- (#704) ✨ Add hover state to component with descriptive information - @XuTheBunny
- (#702) 🔥 Remove study grid look form study list view - @XuTheBunny
- (#701) ✨ Persist study list column sort state - @XuTheBunny
=> 🏷 Release 0.13.1

src/documents/components/FileActionButtons/FileActionButtons.js, src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
♻️ Add download url to download button in file list
♻️ Add download url to download button in file detail<img width="477" alt="Screen Shot 2020-05-15 at 6 09 51 PM" src="https://user-images.githubusercontent.com/32206137/82101789-7e593080-96db-11ea-9426-b73315c7db83.png">
Closes #708
=> ♻️ Turn download links into a tags

.circleci/config.yml, cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js, src/common/globals.js, src/documents/components/FileList/FileElement.js, src/documents/components/FileList/FileList.js, src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/documents/components/ListFilterBar/ListFilterBar.js, src/documents/views/StudyFilesListView.js
Restyles the document file listing within a study.
- Remove sort drop down
- Allow table headers to sort documents
- Remove document description from name, add popup instead
- Add 'last updated' column to document table
- Remove small device responsive layout
Closes #706
=> ✨ Document list sorting restyle

src/components/StudyHeader/StudyHeader.js, src/forms/StudyInfoForm/NewStudyForm.js, src/state/fragments.js, src/views/StudyInfoView.js
✨ Add slack notify checkbox on study info page
✨ Add study slack channel name on study header
=> ✨ Add slack notify checkbox on study info page

src/analyticsTracking/AmplitudeUser.js, src/components/Header/Header.js
Adds more fields to user identities and removes old ones that are no longer used.
=> 📈 Enrich profile properties for analytics

src/common/enums.js, src/components/StudyHeader/StudyHeader.js
=> ✨ Add icons for new event types

CHANGELOG.md, package.json
Exchange invite tokens for new users.
- Emojis: 🐛 x5, 🖼 x1, ✨ x8, 📈 x1, ♻️ x1
- Categories: Fixes x5, Other Changes x2, Additions x9
- [#729](https://github.com/kids-first/kf-ui-data-tracker/pull/729) - 🐛 Check expiration time for token validation - [595b8226](https://github.com/kids-first/kf-ui-data-tracker/commit/595b8226b620bb884354595631c3a7049f9da8aa) by [dankolbman](https://github.com/dankolbman)
- [#728](https://github.com/kids-first/kf-ui-data-tracker/pull/728) - 🐛 Include token when logging users into invite view - [ddec9732](https://github.com/kids-first/kf-ui-data-tracker/commit/ddec97325bac8389344dcd06625e0805a65d4560) by [dankolbman](https://github.com/dankolbman)
- [#727](https://github.com/kids-first/kf-ui-data-tracker/pull/727) - 🖼 Add logo for emails - …
=> 🏷 Release 0.14.0

src/admin/views/ConfigurationView.js, src/components/StudyList/StudyTable.js
Error1: Missing unique keys on table row and table cell:
Error2: Table cell content is null or boolean value
Error3: Trying to render the table before data arrives
=> 🐛 Fix unique key error on study and configuration tables

src/App.css, src/components/StudyHeader/StudyHeader.js, src/views/NavBarView.js
Has slack channel name:
No slack channel name exist:
Add slack channel name:
Edit slack channel name:
Update slack channel name with error:
Submitting loading:
Closes #731
=> ✨ Allow slack channel to be updated

src/components/StudyHeader/StudyHeader.js, src/documents/components/FileList/FileElement.js
🐛 Fix study header missing release data
🐛 Fix study document list missing description
=> 🐛 Fix study header and document loading error

.github/ISSUE_TEMPLATE/feature_request.md
Updates the issue template to be more streamlined.
=> 📝 Update issue template

src/routes/TrackedRoute.js
Only add `utm_source` prop to Amplitude event properties when url contains `?utm_source=XXX`
URL: `http://localhost:3000/study/SD_W2PQV9FJ/logs?utm_source=slack`
URL: `http://localhost:3000/study/SD_W2PQV9FJ/releases`
Closes #752
=> ✨ Include referrals in tracked routes

.github/workflows/gh_release.yml, CHANGELOG.md
- Emojis: ✨ x2, ♻️ x1, 📝 x1
- Categories: Additions x2, Other Changes x1, Documentation x1
- [#754](https://github.com/kids-first/kf-ui-data-tracker/pull/754) - ✨ Include referrals in tracked routes - [2c794ce4](https://github.com/kids-first/kf-ui-data-tracker/commit/2c794ce4914f163da50b6e7ab4f0dfc0830770ef) by [XuTheBunny](https://github.com/XuTheBunny)
- [#753](https://github.com/kids-first/kf-ui-data-tracker/pull/753) - ✨ Add missing fields to configuration page - [4f0c0d83](https://github.com/kids-first/kf-ui-data-tracker/commit/4f0c0d83673af3af48336849e33cb321475c73f0) by [XuTheBunny](https://github.com/XuTheBunny)
- [#747](https://github.com/kids-first/kf-ui-data-tracker/pull/747) - ♻️ Always display bulk document actions - …
=> 🏷 Release 0.14.3

cypress/integration/documents/document_list.spec.js, src/documents/components/FileList/FileList.js
Previously the sorting method was given invalid values.
Closes #748
=> 🐛 Fix document sorting by last updated date

cypress/integration/studies/study_list.spec.js, cypress/integration/studyInfo/slack-update.spec.js, src/App.css, src/components/StudyHeader/StudyHeader.js, src/components/StudyList/StudyList.js, src/components/StudyList/StudyTable.js
✨ Add slack channel and bucket to study list column options
💄 Adjust study list option bar size with responsive look
Closes #760
Closes #757
=> ✨ Include slack channel as study column

src/forms/LinkStudyForm.js
Search by study name:
Search by kf ID:
Closes #762
=> ✨ Make study link dropdown searchable

cypress/integration/documents/document_detail.spec.js, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileList/FileList.js, src/documents/components/VersionList/VersionItem.js, src/documents/components/VersionList/__tests__/VersionItem.test.js, src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap, src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
🔥 Remove approval status from documents
🔥 Remove approval status from document version list
🔥 Remove warning message when approval status is changes needed
Closes #756
=> 🔥 Remove approval status from documents

src/forms/StudyInfoForm/NewStudyForm.js, src/views/NewStudyView.js
=> ♻️ Disable submit button after creating a study

src/forms/StudyInfoForm/NewStudyForm.js, src/forms/StudyInfoForm/Steps/InfoStep.js, src/forms/StudyInfoForm/Steps/LogisticsStep.js
🔥 Remove Cavatica project selection from create study form
Closes #768
Ref https://github.com/kids-first/kf-api-study-creator/pull/424
=> 🔥 Remove default Cavatica projects for new studies

src/components/StudyList/StudyTable.js
=> 🐛 Fix study table sorting error on expected samples column

cypress/integration/invites/invite_user.spec.js, src/App.css, src/admin/queries.js, src/admin/views/PendingInvitesView.js, src/admin/views/index.js, src/components/Header/Header.js, src/components/StudyHeader/StudyHeader.js, src/routes/index.js
=> ✨ Add admin screen for pending invites

src/components/StudyList/StudyList.js, src/documents/components/VersionList/VersionList.js, src/documents/modals/NewVersionModal/NewVersionFlow.js, src/documents/modals/UploadWizard/UploadSteps/ChooseMethodStep.js, src/documents/modals/UploadWizard/UploadSteps/DocumentSelectionStep.js, src/documents/modals/UploadWizard/UploadSteps/SuccessStep.js, src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js, src/documents/modals/UploadWizard/UploadWizard.js, src/documents/views/NewDocumentView.js
Add analytics events for new documents and version uploads.
=> 📈 Add tracking to document uploads

cypress/integration/documents/document_detail.spec.js, cypress/integration/invites/invite_user.spec.js, cypress/integration/studies/study_list.spec.js, cypress/integration/studyInfo/collaborators.spec.js, src/components/CollaboratorsList/CollaboratorItem.js, src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap, src/views/CollaboratorsView.js
Fixes outstanding issues with integration tests.
=> 🐛 Fix tests

CHANGELOG.md, package.json
- Emojis: ✨ x1
- Categories: Additions x1
- [#773](https://github.com/kids-first/kf-ui-data-tracker/pull/773) - ✨ Add collaborator roles - [afd11d58](https://github.com/kids-first/kf-ui-data-tracker/commit/afd11d58ae0f861090a9a59e05a0592ca955da5f) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 0.16.0

cypress/integration/invites/invite_user.spec.js, src/App.css, src/forms/InviteForm.js, src/modals/InviteModal.js
'Add to Invite List' button is enabled when has input
Repeated email input would raise error
Can add multiple emails to the invite list and remove one or all of them
'Send Email Invite' button is enabled when has one or more email inputs
Use blue arrow indicating invite is sending
Use green checkmark indicating invite is successfully sent
Use red warning sign indicating errors (invalid email address)
Repeated invite will raise error (when there is still a valid referral token attached to this email)
Closes #780
=> ✨ Add ability to add multiple users at once for email invites

src/documents/components/FileDetail/FileDetail.js, src/documents/components/VersionList/VersionItem.js, src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap, src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap, src/documents/components/helpers/BaseHelper.js
💄 Use same user avatar component look for file detail and version list - Closes #782
💄 Add hover cursor to version list item - Closes #783 
💄 Add popup to version list item download button - Closes #784
💄 Add popup to file detail download button
=> 💄 Refactor UI for document detail page

cypress/integration/documents/document_detail.spec.js, src/documents/forms/EditDocumentForm.js, src/documents/forms/__tests__/EditDocumentForm.test.js, src/documents/modals/EditDocumentModal.js, src/documents/views/FileDetailView.js, src/documents/views/StudyFilesListView.js
Administrators: Can edit document title, type, tags, and description. Can edit approval status.
Investigators: Can edit document title, type, tags, and description. Cannot edit approval status, can only view it.
Backend PR: https://github.com/kids-first/kf-api-study-creator/pull/429
=> ♻️ Accept permission for investigator to edit document meta

src/components/EventList/EventList.js, src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
=> 🐛 Fix misspelled event description

src/modals/CreatingStudyModal.js
=> ✨ Add status for slack channel on study creation modal

src/documents/components/ListFilterBar/ListFilterBar.js, src/documents/views/StudyFilesListView.js
Update search box place holder and add popup showing we support search by file name, description and KF iD:
Close #812
=> ✨ Support search documents by KF ID

cypress/integration/documents/document_list.spec.js, src/components/StudyList/KfId.js, src/documents/components/FileList/FileElement.js, src/documents/components/FileList/FileList.js, src/documents/components/ListFilterBar/ListFilterBar.js, src/documents/views/StudyFilesListView.js
=> ✨ Add checkbox in filter bar to show hide file ID column on file table

src/App.css, src/documents/components/FileDetail/FileTags.js, src/documents/components/ListFilterBar/ListFilterBar.js, src/documents/views/StudyFilesListView.js
✨ Add tag filter option for untagged files
✨ Add multi-selection for tag filter with intersect or union option
Closes #820 
Closes #821 
Closes #823
=> ✨ Add multi-selection for tag filter with untagged option

CHANGELOG.md
- Emojis: 💄 x3, ✨ x5, ♻️ x3, 🐛 x1, ? x2
- Categories: Other Changes x8, Additions x5, Fixes x1
- [#822](https://github.com/kids-first/kf-ui-data-tracker/pull/822) - 💄 Revise error message for studies list - [b6c38626](https://github.com/kids-first/kf-ui-data-tracker/commit/b6c3862642af4991290d00839a2dfdf4fc8e1d94) by [dankolbman](https://github.com/dankolbman)
- [#825](https://github.com/kids-first/kf-ui-data-tracker/pull/825) - ✨ Add multi-selection for tag filter with untagged option - [19848653](https://github.com/kids-first/kf-ui-data-tracker/commit/19848653e5f64b9682be6a16a0b7375bac0541e4) by [XuTheBunny](https://github.com/XuTheBunny)
- [#832](https://github.com/kids-first/kf-ui-data-tracker/pull/832) - ♻️ Use display name on user list, events, and collaborators - …
=> 🏷 Release 0.16.1

src/App.css, src/components/StudyHeader/StudyHeader.js, src/views/NavBarView.js
Adds background to the study header component.
=> 🎨 Add background to study header

cypress/integration/studies/study_list.spec.js, src/common/urls.js, src/documents/components/FileDetail/AnalysisSummary.js, src/documents/components/VersionList/VersionItem.js, src/documents/forms/NewDocumentForm.js, src/documents/forms/NewVersionForm.js, src/documents/mutations.js, src/documents/routes.js, src/documents/views/FileDetailView.js, src/documents/views/StudyFilesListView.js, src/documents/views/UploadView.js, src/documents/views/index.js, src/routes/index.js
Updates the upload flow to first upload a file as a new version and then create a document for that version with additional information.
Closes #46
Closes #811
Closes #830
Closes #835
=> ♻️ New document upload flow

CHANGELOG.md
- Emojis: ♻️ x1, ✨ x1, 🎨 x1, 🐛 x1, 🔥 x1
- Categories: Other Changes x2, Additions x1, Fixes x1, Removals x1
- [#840](https://github.com/kids-first/kf-ui-data-tracker/pull/840) - ♻️ New document upload flow - [5a0e2cc2](https://github.com/kids-first/kf-ui-data-tracker/commit/5a0e2cc2ce27cf729dafa4887416032dcf3784bb) by [dankolbman](https://github.com/dankolbman)
- [#833](https://github.com/kids-first/kf-ui-data-tracker/pull/833) - ✨ Add analysis summary to file detail - [22f9b23a](https://github.com/kids-first/kf-ui-data-tracker/commit/22f9b23ab121fdbdef95a8431f640f3ec441f347) by [dankolbman](https://github.com/dankolbman)
- [#841](https://github.com/kids-first/kf-ui-data-tracker/pull/841) - 🎨 Add background to study header - [83a2db4e](https://github.com/kids-first/kf-ui-data-tracker/commi …
=> 🏷 Release 0.16.2

src/documents/views/StudyFilesListView.js
Updates the drop zone in the study's file list view to forward the user to the new upload flow.
=> ♻️ Redirect the upload drop zone to new flow

CHANGELOG.md
- Emojis: ♻️ x1, 🐛 x1
- Categories: Other Changes x1, Fixes x1
- [#843](https://github.com/kids-first/kf-ui-data-tracker/pull/843) - ♻️ Redirect the upload drop zone to new flow - [04a2bdde](https://github.com/kids-first/kf-ui-data-tracker/commit/04a2bdde2409c2708a8a0f8f7ae9be363a1598ca) by [dankolbman](https://github.com/dankolbman)
- [#844](https://github.com/kids-first/kf-ui-data-tracker/pull/844) - 🐛 Pass correct study object to upload bar - [10adcd92](https://github.com/kids-first/kf-ui-data-tracker/commit/10adcd92c8b38cfec0cebb3a0b4567dcf489fabe) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 0.16.3

Jenkinsfile, netlify.toml
Uses Netlify build hooks to trigger a deployment to production whenever there is a tagged commit on master.
=> 👷 Remove Jenkins

.circleci/config.yml, netlify.toml
Updates the dev url to new location and prohibits production from deploying on every master commit.
=> 👷 Update CI

src/documents/forms/NewDocumentForm.js, src/documents/mutations.js, src/documents/views/UploadView.js
The file type enum has changed from `FileFileType` to `FileType` and needs to be updated.
=> ♻️ Update FileType enum

.circleci/config.yml
Separates the deployment into its own workflow.
=> 👷 Add individual workflow for deployment

.circleci/config.yml, src/common/enums.js
=> 💄 Add icons for file analysis and version meta permissions

cypress/integration/documents/document_config.spec.js, package.json, src/common/enums.js, src/components/CopyButton/CopyButton.js, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileDetail/FileDetailModal.js, src/documents/modals/ExtractConfigModal.js, src/documents/modals/index.js, src/documents/views/FileDetailView.js, yarn.lock
=> ✨ Add document extract config modal to preview and download config file 

.circleci/config.yml, netlify.toml
Deploys bundles to cloudfront for tagged releases.
=> 👷 Deploy production to cloudfront

cypress/integration/invites/invite_user.spec.js, src/admin/queries.js, src/admin/views/UsersView.js, src/common/notificationUtils.js, src/components/StudyList/IngestionStatus.js, src/components/StudyList/PhenotypeStatus.js, src/components/StudyList/SequencingStatus.js, src/state/fragments.js, src/state/queries.js
Reduces the amount of information requested to retrieve all studies to display on the study list view.
=> ⚡ Pare down fields requested for all studies

src/documents/components/PreviewTable/PreviewTable.js, src/documents/views/VersionPreviewView.js
=> ♻️ Refactor preview table for sorting and reducing bundle size

.circleci/config.yml, src/documents/forms/EditDocumentForm.js, src/documents/forms/__tests__/EditDocumentForm.test.js, src/documents/fragments.js, src/documents/modals/EditDocumentModal.js
=> ✨ Disable the file type selection option if file is not qualified

src/common/enums.js, src/documents/forms/NewDocumentForm.js, src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap, src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Adds 'Participant Demographic and Administrative File' and 'Family Trio' file types and a 'read more' link for file type sections.
=> ✨ New expedited types

netlify.toml, src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
Updates the QA api url for the study creator.
=> 🔧 Update QA api url

CHANGELOG.md
- Emojis: 🔧 x1, ✨ x6, 💄 x2, ♻️ x2, ⚡ x1, 👷 x4, 🎨 x1, ⬆️ x2
- Categories: Other Changes x7, Additions x6, Ops x6
- [#879](https://github.com/kids-first/kf-ui-data-tracker/pull/879) - 🔧 Update QA api url - [2bb11a59](https://github.com/kids-first/kf-ui-data-tracker/commit/2bb11a59068a3d604b7fce4680771637823407cf) by [dankolbman](https://github.com/dankolbman)
- [#875](https://github.com/kids-first/kf-ui-data-tracker/pull/875) - ✨ New expedited types - [1312ee6b](https://github.com/kids-first/kf-ui-data-tracker/commit/1312ee6bb8e653a48b963b5121d003217ecb5fdf) by [dankolbman](https://github.com/dankolbman)
- [#877](https://github.com/kids-first/kf-ui-data-tracker/pull/877) - ✨ Disable the file type selection option if file is not qualified - …
=> 🏷 Release 0.17.0

CHANGELOG.md
- Emojis: 🔧 x1
- Categories: Other Changes x1
- [#893](https://github.com/kids-first/kf-ui-data-tracker/pull/893) - 🔧 Redirect host - [e2dac988](https://github.com/kids-first/kf-ui-data-tracker/commit/e2dac988a453a0b8426a8440008deff50270e300) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 0.17.2

src/admin/views/UsersView.js
=> 🐛 Fix user group dropdown in user page not updating

cypress/integration/studies/add_study.spec.js, cypress/integration/studies/study_list.spec.js, cypress/integration/studies/study_statuses.spec.js, src/components/StudyList/StudyList.js
- For all new users, default to display all the studies.
- For users who cleared their local storage (not having `onlyMyStudies` value), default to display all the studies.
- For user who have `onlyMyStudies` value, toggling the only showing my studies based on its value.
=> ♻️ Default showing only my studies to be false

src/App.css, src/documents/components/FileActionButtons/FileActionButtons.js, src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/documents/components/VersionList/VersionItem.js, src/documents/components/VersionList/__tests__/VersionItem.test.js, src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap, src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
=> ✨ Add copy download url button and copy version kf ID button

src/releases/components/ServiceList/ServiceList.js, src/releases/components/ServiceList/index.js, src/releases/components/helpers/NewServiceHelp.js, src/releases/components/helpers/ServicesHelp.js, src/releases/components/helpers/index.js, src/releases/forms/NewServiceForm.js, src/releases/fragments.js, src/releases/mutations.js, src/releases/queries.js, src/releases/routes.js, src/releases/views/NavigationView.js, src/releases/views/NewServiceView.js, src/releases/views/ServicesListView.js, src/releases/views/index.js
**Task services list:**
**Task services list with error on enable/disable:**
**Register a new task service:**
**Register a new task service with invalid endpoint error:**
Closes #870
=> ✨ Add services list view and register new service view to release sub app

src/App.css, src/releases/forms/NewReleaseForm.js, src/releases/views/NewReleaseView.js
**Run new release form with cancel button:**
**Confirm window with cancel button:**
=> ✨ Update run new release flow with confirm widow

src/releases/forms/UpdateServiceForm.js, src/releases/queries.js, src/releases/routes.js, src/releases/views/ServiceDetailView.js, src/releases/views/index.js
**Service detail view:**
**Service detail view in loading:**
**Service detail view with error:**
**Editing service detail:**
**Editing service detail with url error warning:**
Closes #871
=> ✨ Add service detail view to release sub app feature

CHANGELOG.md
- Emojis: ✨ x4, 💄 x1
- Categories: Additions x4, Other Changes x1
- [#898](https://github.com/kids-first/kf-ui-data-tracker/pull/898) - ✨ Add services list view and register new service view to release sub app - [8f7c7c1f](https://github.com/kids-first/kf-ui-data-tracker/commit/8f7c7c1ff0e9af5b072717eb51e40f98595c44b8) by [XuTheBunny](https://github.com/XuTheBunny)
- [#905](https://github.com/kids-first/kf-ui-data-tracker/pull/905) - ✨ Add service detail view to release sub app feature - [b1995ea9](https://github.com/kids-first/kf-ui-data-tracker/commit/b1995ea9be64879eabb6149ee80b4bf74f0798d0) by [XuTheBunny](https://github.com/XuTheBunny)
- [#907](https://github.com/kids-first/kf-ui-data-tracker/pull/907) - 💄 UI updates around releases and services page - …
=> 🏷 Release 0.18.0

cypress/integration/studies/study_statuses.spec.js, src/components/StudyList/StudyList.js, src/components/StudyList/StudyTable.js
=> 🔥  Remove status fields from study table

package.json, src/App.css, src/admin/components/JobsList/JobsList.js, src/admin/components/JobsList/index.js, src/admin/queries.js, src/admin/views/ConfigurationView.js, src/admin/views/LogView.js, src/admin/views/LogsView.js, src/admin/views/index.js, src/components/Header/Header.js, src/routes/index.js, src/state/queries.js, yarn.lock
Adds an administrative page where users can see stdout logs for completed jobs.
=> 🔈 Add task logs

src/documents/components/FileActionButtons/FileActionButtons.js, src/documents/components/FileDetail/FileDetail.js, src/documents/components/ListFilterBar/BatchActions.js, src/documents/components/ListFilterBar/ListFilterBar.js
=> 📈 Add analytics to file actions and file batch actions

src/common/enums.js, src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap, src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Adds a new expedited file type for the Genomic Workflow Output Manifest to support https://github.com/kids-first/kf-api-study-creator/issues/492
=> ✨ Add genomic workflow output manifest to file types

src/releases/forms/NewReleaseForm.js, src/releases/views/NewReleaseView.js
Adds service list to release planner form
Fixes description not being saved for new release
=> ♻ New release fixes

.circleci/config.yml, package.json, src/documents/components/FileDetail/FileDescription.js, src/documents/forms/EditDocumentForm.js, src/documents/forms/NewDocumentForm.js, src/documents/forms/NewVersionForm.js, src/releases/components/ReleaseDetail/MarkdownEditor.js, src/releases/forms/NewReleaseForm.js, yarn.lock
=> 🐛 Fix markdown editor codeblock indent conversion

README.md
I went through the README to try and setup the Data Tracker dev env and came across some things. Here's an updated README with some fixes/clarifications. Not sure if all are valid (do we still use kf-data-stack??)
=> 📝 Update setup steps in README

CHANGELOG.md
- Emojis: 📝 x1, 🐛 x1, 👷‍♂️ x1, ♻ x1, ✨ x1, 🔥 x1, 📈 x1, 🔈 x1
- Categories: Documentation x1, Fixes x1, Other Changes x3, Additions x2, Removals x1
- [#903](https://github.com/kids-first/kf-ui-data-tracker/pull/903) - 📝 Update setup steps in README - [62f3ca56](https://github.com/kids-first/kf-ui-data-tracker/commit/62f3ca566aa3e19ddb1b8bb3d2d7621f398691d6) by [znatty22](https://github.com/znatty22)
- [#914](https://github.com/kids-first/kf-ui-data-tracker/pull/914) - 🐛 Fix markdown editor codeblock indent conversion - [9e55d120](https://github.com/kids-first/kf-ui-data-tracker/commit/9e55d1201003b5e80cd2768e25dde6c0354fe935) by [XuTheBunny](https://github.com/XuTheBunny)
- [#913](https://github.com/kids-first/kf-ui-data-tracker/pull/913) - 👷‍♂️ Use netlify production as qa - …
=> 🏷 Release 0.18.1

src/App.css, src/common/enums.js, src/components/CavaticaProjectList/CavaticaProjectItem.js, src/components/CavaticaProjectList/StudyProjects.js, src/components/StudyInfo/CavaticaCounts.js
**Cavatica project type label color:**
- Delivery: red
- Analysis: green
- Research: yellow
- Unknown: grey
**Cavatica tab for each study:**
**Admin Cavatica Projects page:**
Closes #918
=> ✨ Display colored label for Cavatica project type

src/documents/modals/NewVersionModal/DescriptionStep.js, src/documents/modals/NewVersionModal/NewVersionFlow.js, src/documents/modals/NewVersionModal/__tests__/NewVersionFlow.test.js, src/documents/modals/VersionInfoModal.js
=> ✨ Use markdown for version summary input and display

cypress/integration/documents/document_config.spec.js, cypress/integration/documents/document_detail.spec.js, src/App.css, src/documents/components/FileDetail/FileDescription.js, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileDetail/FileDetailModal.js, src/documents/components/FileDetail/FileName.js, src/documents/components/FileDetail/FileTags.js, src/documents/components/FileDetail/Timelines.js, src/documents/components/FileDetail/VersionCard.js, src/documents/fragments.js, src/documents/modals/EditDocumentModal.js, src/documents/views/FileDetailView.js
=> 💄 Update UI design for document detail page

CHANGELOG.md
- Emojis: 💄 x1, ✨ x3
- Categories: Other Changes x1, Additions x3
- [#928](https://github.com/kids-first/kf-ui-data-tracker/pull/928) - 💄 Update UI design for document detail page - [f54866a4](https://github.com/kids-first/kf-ui-data-tracker/commit/f54866a4f3746f2cebb9affd12274a7159463749) by [XuTheBunny](https://github.com/XuTheBunny)
- [#926](https://github.com/kids-first/kf-ui-data-tracker/pull/926) - ✨ Use markdown for version summary input and display - [6685d38a](https://github.com/kids-first/kf-ui-data-tracker/commit/6685d38a8d38c6e8eac34a1be2e351f29ec1aba2) by [XuTheBunny](https://github.com/XuTheBunny)
- [#925](https://github.com/kids-first/kf-ui-data-tracker/pull/925) - ✨ Display colored label for Cavatica project type - …
=> 🏷 Release 0.18.2

src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileDetail/VersionCard.js, src/documents/views/VersionPreviewView.js
=> ✨ Add file summary modal to file preview page with learn more button

src/releases/components/ReleaseDetail/Log.js, src/releases/components/ReleaseDetail/LogViewer.js, src/releases/components/ReleaseDetail/MarkdownEditor.js, src/releases/components/ReleaseDetail/ReleaseActions.js, src/releases/components/ReleaseDetail/ReleaseHeader.js, src/releases/components/ReleaseHeader/ReleaseHeader.js, src/releases/components/ReleaseTaskList/ReleaseTaskList.js, src/releases/components/ReleaseTaskList/index.js, src/releases/queries.js, src/releases/views/NavigationView.js, src/releases/views/ReleaseDetailView.js
Update the layout of the release detail view to more closely resemble that of a document detail view.
=> 🎨 Release detail restyle

src/documents/modals/ExtractConfigModal.js
=> 🐛 Fix typo in extract config download code button popup

src/components/StudyNavBar/StudyNavBar.js, src/routes/index.js
=> 🐛 Default path /study/kfId/ to documents tab

src/components/StudyList/StudyList.js
=> ✨ Allow search study by slack channel name

.circleci/config.yml, cypress/integration/documents/document_config.spec.js, cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js, cypress/integration/invites/invite_user.spec.js, cypress/integration/studies/study_list.spec.js, cypress/integration/studyInfo/collaborators.spec.js, docker-compose.yml, src/modals/InviteModal.js
Fixes broken end-to-end tests.
=> ✅ Fix tests

src/releases/components/StudyTable/StudyTable.js, src/releases/forms/NewReleaseForm.js
Allows users to filter down studies by a search string within the new release form. This helps find the study of interest more quickly when creating a release.
Closes #973
=> ✨ Search studies within new release form

src/releases/components/ReleaseTable/ReleaseController.js, src/releases/components/ReleaseTable/ReleaseTable.js, src/releases/components/ReleaseTable/index.js, src/releases/queries.js, src/releases/views/HomeView.js
Add pagination for releases so users may scroll through all releases.
Closes #970
=> ✨ Release pagination

src/App.css, src/admin/common/bannerUtils.js, src/admin/components/BannerTable/ActionButtons.js, src/admin/components/BannerTable/BannerDate.js, src/admin/components/BannerTable/BannerMessage.js, src/admin/components/BannerTable/BannerTable.js, src/admin/components/BannerTable/BannerToggle.js, src/admin/components/BannerTable/Creator.js, src/admin/components/BannerTable/Severity.js, src/admin/components/BannerTable/index.js, src/admin/forms/BannerForm.js, src/admin/mutations.js, src/admin/queries.js, src/admin/views/BannersView.js, src/admin/views/EditBannerView.js, src/admin/views/NewBannerView.js, src/admin/views/index.js, src/common/dateUtils.js, src/components/Header/AppBanner.js, src/components/Header/Header.js, src/components/Header/index.js, src/routes/index.js
Closes #958 
A new feature to create, update, delete, and edit message banners that will be persistently displayed on Data Tracker when we want to notify users of something important (e.g. maintenance, new features, etc)
=> ✨ App banners

package.json, src/App.css, src/releases/components/ReleaseActivity/ReleaseActivity.js, src/releases/components/ReleaseActivity/calendar.js, src/releases/components/ReleaseActivity/index.js, src/releases/components/ReleaseBarChart/ReleaseBarChart.js, src/releases/components/ReleaseBarChart/bar.js, src/releases/components/ReleaseBarChart/index.js, src/releases/queries.js, src/releases/routes.js, src/releases/views/NavigationView.js, src/releases/views/StatsView.js, src/releases/views/index.js, yarn.lock
Add a statistics view for releases where we can summarize recent activity and performance of releases.
Closes #972
=> 📈 Release charts

src/admin/components/JobsList/JobsList.js, src/admin/queries.js, src/admin/views/LogsView.js
Allow users to filter logs by the job they belong to.
Closes #969
=> ✨ Filter logs by job

cypress/integration/invites/invite_user.spec.js, src/admin/views/PendingInvitesView.js
Allow administrators to resend an email invite if an invite was allowed to expire.
Closes #956
=> ✨ Allow expired invites to be resent

cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js, package.json, src/App.css, src/common/treeDataUtils.js, src/documents/components/FileDetail/FileName.js, src/documents/components/FileList/FileFolder.js, src/documents/components/FileList/FolderItem.js, src/documents/views/StudyFilesListView.js, yarn.lock
Study document folder mode: (Newly uploaded file will be added to the bottom)
Highlight search result:
Create new folder or sub-folder
Editing document title:
Editing folder name:
Deleting document:
Deleting folder:
=> ✨ Add file folder feature for study documents

src/App.css, src/components/StudyList/InvestigatorName.js, src/components/StudyList/StudyList.js, src/components/StudyList/StudyTable.js, src/forms/StudyInfoForm/NewStudyForm.js, src/forms/StudyInfoForm/Steps/InfoStep.js, src/state/fragments.js, src/state/queries.js
Adds an investigator name to studies to aid in organizing and finding studies.
Visible and modifyable in new study form and study info form.
Available as a column in the study table.
Searchable from the study table.
Closes #889
=> ✨ Add investigator to study

CHANGELOG.md
- Emojis: ✨ x11, 📈 x1, ⬆️ x1, ✅ x1, 💄 x2, 🐛 x3, 🎨 x2, 🔥 x1, 🔧 x1
- Categories: Additions x12, Ops x1, Other Changes x6, Fixes x3, Removals x1
- [#943](https://github.com/kids-first/kf-ui-data-tracker/pull/943) - ✨ Add file folder feature for study documents - [eec4fa13](https://github.com/kids-first/kf-ui-data-tracker/commit/eec4fa13c5f5a6e3e2ddc1fe24a401a9668b2eaa) by [XuTheBunny](https://github.com/XuTheBunny)
- [#981](https://github.com/kids-first/kf-ui-data-tracker/pull/981) - ✨ Allow expired invites to be resent - [ffd7ee3f](https://github.com/kids-first/kf-ui-data-tracker/commit/ffd7ee3f9f34a1263a453f75204eebb7e75cdb12) by [dankolbman](https://github.com/dankolbman)
- [#980](https://github.com/kids-first/kf-ui-data-tracker/pull/980) - ✨ Filter logs by job - …
=> 🏷 Release 0.19.0

CHANGELOG.md
- Emojis: 🔥 x1, ✨ x1, 🐛 x1
- Categories: Removals x1, Additions x1, Fixes x1
- [#995](https://github.com/kids-first/kf-ui-data-tracker/pull/995) - 🔥 Remove unused status fields - [352b8866](https://github.com/kids-first/kf-ui-data-tracker/commit/352b886654c9a9bacfcf52e10e4087efdea1386a) by [dankolbman](https://github.com/dankolbman)
- [#989](https://github.com/kids-first/kf-ui-data-tracker/pull/989) - ✨ Add file folder detail view with folder tree view on the side - [369e990f](https://github.com/kids-first/kf-ui-data-tracker/commit/369e990f37fced4cb2076783ca8c8b4019a1624c) by [XuTheBunny](https://github.com/XuTheBunny)
- [#961](https://github.com/kids-first/kf-ui-data-tracker/pull/961) - 🐛 Fix footer backend version link - [d74a2515](https://github.com/kids-first/kf-ui-data-tracker/commit/ …
=> 🏷 Release 0.19.1

src/components/Header/DevHeader.js
Hide the dev bar if the `DEV_BAR` environment variable is not set.
=> 🐛 Hide devbar if variable not set

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#997](https://github.com/kids-first/kf-ui-data-tracker/pull/997) - 🐛 Hide devbar if variable not set - [2de7b2f9](https://github.com/kids-first/kf-ui-data-tracker/commit/2de7b2f90c47985fe3a5359da1f3c17dad51cd47) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 0.19.2

package.json, src/releases/components/ReleaseDetail/ReleaseActions.js, yarn.lock
=> ✨ Show confetti when successfully publish the release

CHANGELOG.md
- Emojis: 💄 x1, 🔥 x1, ✨ x2, ⬆️ x1
- Categories: Other Changes x1, Removals x1, Additions x2, Ops x1
- [#1010](https://github.com/kids-first/kf-ui-data-tracker/pull/1010) - 💄 Refactor study list sizing and add favorite studies search - [14e17488](https://github.com/kids-first/kf-ui-data-tracker/commit/14e17488d1e4ee819ac8e7c1dea3f85af26659fe) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1011](https://github.com/kids-first/kf-ui-data-tracker/pull/1011) - 🔥 Remove roles from user fragment - [46f210be](https://github.com/kids-first/kf-ui-data-tracker/commit/46f210bec7a001a43a869ff2d8ad68979f235cbb) by [dankolbman](https://github.com/dankolbman)
- [#1005](https://github.com/kids-first/kf-ui-data-tracker/pull/1005) - ✨ Show confetti when successfully publish the release - …
=> 🏷 Release 0.20.0

src/components/StudyNavBar/StudyNavBar.js, src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
=> 🐛 Fix study nav bar with newly added reviews tab

src/admin/components/JobsList/JobsList.js, src/admin/components/UserList/PermissionGroup.js, src/common/enums.js
=> 💄 Add icons for new release related permission types

src/common/enums.js
=> 💄 Add icons for data review events and data validation events

.circleci/config.yml, craco.config.js, src/@next/routes.tsx, src/routes/index.js, src/views/NotFoundView.js
Adds the router for the `@next` application under the `/next` path.
Changes the NotFoundView to match paths by partial strings rather than exact matches so that we may avoid rendering it under general subroutes.
Fixes #1023
=> ✨ Add next routes

.circleci/config.yml, craco.config.js, src/@next/routes.tsx, src/routes/index.js, src/views/NotFoundView.js
Reverts kids-first/kf-ui-data-tracker#1024
=> ⏪ Revert next routes

src/components/StudyList/StudyTable.js, src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap, src/documents/components/FileFolder/FileFolder.js, src/documents/modals/NewVersionModal/DescriptionStep.js, src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js, src/documents/views/ReviewListView.js, src/documents/views/StartReviewView.js, src/documents/views/StudyFilesListView.js, src/releases/views/ServiceDetailView.js
Instead of using `<h2>AAA</h2>` directly in frontend, use Semantic Header component as `<Header as='h2'>AAA</Header>`
=> 💄 Use Semantic header component replacing the default HTML header

.circleci/config.yml
=> ⚙️ Bump Node version to 16 in tests config

src/releases/components/ReleaseTable/CreatedAt.js, src/releases/components/ReleaseTable/ReleaseTable.js
=> 💄 Update release table started at time format

src/documents/components/FileDetail/FileTags.js, src/documents/components/FileFolder/FileFolder.js, src/documents/components/FileFolder/FileSimpleElement.js, src/documents/components/FileFolder/FileSimpleList.js, src/documents/components/FileList/FileElement.js, src/documents/components/FileList/FileList.js, src/documents/components/ReviewFiles/ReviewFileElement.js, src/documents/components/ReviewFiles/ReviewFileList.js, src/documents/components/ReviewFiles/ReviewFileSection.js, src/documents/views/StudyFilesListView.js
✨ Click on tag to filter files from file table
✨ Click on tag to search the files from folder tree
✨ Click on tag to filter files from review add document table
Closes #1002
=> ✨ Click on tag to filter files from document list and review add document table

package.json, src/components/StudyNavBar/StudyNavBar.js, src/forms/StudyInfoForm/NewStudyForm.js, src/forms/StudyInfoForm/Steps/AdditionalFields.js, src/forms/StudyInfoForm/Steps/CustomLink.js, src/forms/StudyInfoForm/Steps/CustomParagraph.js, src/forms/StudyInfoForm/Steps/index.js, src/state/fragments.js, src/views/StudyInfoView.js, yarn.lock
In design:
Customized information field:
JSON Data:
```
{
"time":1622094700268,
"blocks":[
{
"id":"flzeqmPu9A",
"type":"customText",
"data":{
"name":"",
"value":""
}
},
{
"id":"kE6eAxKv65",
"type":"customLink",
"data":{
"name":"",
"value":""
}
}
],
"version":"2.21.0"
}
```
=> ✨ Add additional customized information field for study and save as json string

src/common/enums.js, src/components/CavaticaProjectList/CavaticaProjectList.js, src/documents/modals/UploadWizard/UploadWizard.js, src/modals/EditProjectModal.js, src/views/CavaticaBixView.js
=> 🐛 Fix editing/linking/unlinking Cavatica projects error

src/releases/components/StudyTable/StudyTable.js
=> 🐛 Fix study release version display bug

cypress/fixtures/example.json, cypress/integration/documents/document_config.spec.js, cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js, cypress/integration/studies/study_list.spec.js, cypress/integration/studyInfo/collaborators.spec.js
Updates tests due to mock data changes introduced in kids-first/kf-api-study-creator#632
Backend PR breaks invite and study creation features and tests which will be patched in a subsequent PR.
=> ✅ Update tests for organization changes

src/admin/components/OrganizationList/OrganizationItem.js, src/admin/components/OrganizationList/OrganizationList.js, src/admin/components/OrganizationList/index.js, src/admin/forms/EditOrganizationForm.js, src/admin/fragments.js, src/admin/mutations.js, src/admin/queries.js, src/admin/views/OrganizationsView.js, src/admin/views/index.js, src/components/Header/Header.js, src/routes/index.js
Adds an administrative page to view and modify existing organizations.
=> ✨ Organizations admin view

cypress/integration/studies/add_study.spec.js, cypress/integration/studies/study_list.spec.js, src/views/NewStudyView.js
Attaches the currently active organization when creating a study.
=> ✨ Add org to new studies

cypress/integration/documents/document_config.spec.js, cypress/integration/documents/document_detail.spec.js, cypress/integration/documents/document_list.spec.js, cypress/integration/studies/study_list.spec.js, cypress/integration/studyInfo/collaborators.spec.js, cypress/integration/studyInfo/logs.spec.js
Updates tests to accommodate changes made in the API's mock data.
=> ✅ Update cypress tests for new mock data

src/App.css, src/documents/components/DataValidation/DataValidation.js, src/documents/components/ReviewDetail/ReviewDetail.js, src/documents/components/helpers/DataValidationHelp.js, src/documents/components/helpers/index.js, src/documents/views/DataValidationView.js, src/documents/views/ReviewDetailView.js, src/documents/views/ReviewListView.js, src/documents/views/index.js, src/routes/index.js, src/state/fragments.js, src/state/mutations.js, src/state/queries.js, src/views/NavBarView.js
Show data validation result on review list
Show data validation result on review detail page
Add data validation view with init, running, and completed stage
Closes #1034
Closes #1035
=> ✨ Add data validation page for internal data review with validation report

src/common/enums.js, src/documents/components/FileDetail/FileDetail.js, src/documents/components/FileDetail/SelectElement.js, src/documents/components/FileFolder/FileSimpleElement.js, src/documents/components/FileList/FileElement.js, src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap, src/documents/components/ReviewFiles/ReviewFileElement.js, src/documents/components/UploadSteps/ChooseTypeStep.js, src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap, src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
=> ✨ Update document types to match templates

src/components/Header/Header.js, src/components/StudyList/ActionButtons.js, src/modals/TransferStudyModal.js, src/state/mutations.js, src/state/queries.js
=> ✨ Add feature allows user to transfer study to another organization

src/App.css, src/admin/components/UserList/UserItem.js, src/admin/components/UserList/UserList.js, src/admin/queries.js, src/admin/views/UsersView.js, src/state/mutations.js
=> ✨ Add feature allows user to add or remove member of an organization 

CHANGELOG.md
- Emojis: ✨ x8, 🐛 x4, 💄 x5, ⚙️ x1, ⏪ x2, 🎨 x1, ? x1, 🔥 x1
- Categories: Additions x8, Removals x3, Fixes x4, Other Changes x8
- [#1066](https://github.com/kids-first/kf-ui-data-tracker/pull/1066) - ✨ Add feature allows user to add or remove member of an organization - [6cb80572](https://github.com/kids-first/kf-ui-data-tracker/commit/6cb805721a27f7fa1f6661bb805c9918bb9ed3af) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1065](https://github.com/kids-first/kf-ui-data-tracker/pull/1065) - ✨ Add feature allows user to transfer study to another organization - [b356aa77](https://github.com/kids-first/kf-ui-data-tracker/commit/b356aa776eb435c8d3b93bbd040eb97a3fe123f3) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1064](https://github.com/kids-first/kf-ui-data-tracker/pull/1064) - ✨ …
=> 🏷 Release 0.21.0

src/documents/components/ReviewDetail/ReviewVersions.js
Set to all of the file types stored in frontend that have non empty list of required columns.
=> ✨ Set document type groups for review

CHANGELOG.md
- Emojis: ✨ x1, ♻️ x2
- Categories: Additions x1, Other Changes x2
- [#1081](#1081) - ✨ Set document type groups for review - [46b0fc6](46b0fc6) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1079](#1079) - ♻️ Reduce required cols in file types to match backend - [ab9c39f](ab9c39f) by [znatty22](https://github.com/znatty22)
- [#1077](#1077) - ♻️ Replace static site orb with s3 orb - [f52168a](f52168a) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 0.21.1

src/admin/views/TemplatesView.js, src/components/TemplateList/TemplateList.js
=> 🐛 Fix admin templates organization options

src/components/TemplateList/TemplateList.js
=> 🐛 Fix study data template tab displaying error

CHANGELOG.md
- Emojis: 🐛 x2, ✨ x2
- Categories: Additions x2, Fixes x2
- [#1090](https://github.com/kids-first/kf-ui-data-tracker/pull/1090) - 🐛 Fix study data template tab displaying error - [36a0f1c2](https://github.com/kids-first/kf-ui-data-tracker/commit/36a0f1c2842a58649ff9a155855849efcd7b67ec) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1088](https://github.com/kids-first/kf-ui-data-tracker/pull/1088) - 🐛 Fix admin templates organization options - [85980486](https://github.com/kids-first/kf-ui-data-tracker/commit/859804868a235f50e9f2574cdaf23e11bbe5de0b) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1085](https://github.com/kids-first/kf-ui-data-tracker/pull/1085) - ✨ Add template admin view with create/edit/delete template function - …
=> 🏷 Release 0.22.0

src/admin/views/TemplatesView.js, src/components/TemplateList/TemplateList.js, src/forms/DataTemplateForm/DataTemplateForm.js, src/modals/DataTemplateEditModal.js, src/views/DataTemplatesView.js
=> ✨ Add read-only template modal to the list in study data template tab

CHANGELOG.md
- Emojis: ✨ x1
- Categories: Additions x1
- [#1091](https://github.com/kids-first/kf-ui-data-tracker/pull/1091) - ✨ Add read-only template modal to the list in study data template tab - [2879ac26](https://github.com/kids-first/kf-ui-data-tracker/commit/2879ac2682070b3bffacbbefc22f4788aed05f78) by [XuTheBunny](https://github.com/XuTheBunny)
=> 🏷 Release 0.22.1

src/admin/views/EventsView.js, src/common/enums.js, src/components/StudyList/InvestigatorName.js, src/forms/StudyInfoForm/Steps/InfoStep.js
🐛 Fix typo "Principal Investigator" for study info
🐛 Fix invalid null input for Investigator Name on study list
Closes #1106 
💄 Updated icons for new event types
♻️ Add key to admin events filter to support unique key for mapping
Closes #1107
=> 🐛 Minor bug fix around study info and event list

CHANGELOG.md
- Emojis: ♻️ x2, 🐛 x1
- Categories: Fixes x1, Other Changes x2
- [#1114](https://github.com/kids-first/kf-ui-data-tracker/pull/1114) - ♻️ Adjust template field input table experience - [3a135145](https://github.com/kids-first/kf-ui-data-tracker/commit/3a135145d80fb7c8d1b80f7a51c6e0d269e624e2) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1113](https://github.com/kids-first/kf-ui-data-tracker/pull/1113) - ♻️ Refactor study document tab layout and refetch - [861622ed](https://github.com/kids-first/kf-ui-data-tracker/commit/861622ed1dcbff18400e8494bed3f1afc9d0d960) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1112](https://github.com/kids-first/kf-ui-data-tracker/pull/1112) - 🐛 Minor bug fix around study info and event list - …
=> 🏷 Release 0.23.1

src/documents/components/UploadSteps/ChooseTypeStep.js, src/modals/DataTemplateEditModal.js
=> 🐛 Fix view only template missing function error on close

CHANGELOG.md
- Emojis: ✨ x1, 💄 x1, 🐛 x1
- Categories: Additions x1, Fixes x1, Other Changes x1
- [#1117](https://github.com/kids-first/kf-ui-data-tracker/pull/1117) - ✨ Better general file types - [0fa6faf9](https://github.com/kids-first/kf-ui-data-tracker/commit/0fa6faf9a2fe7cdaced0676441e3ad1d4ee7119b) by [znatty22](https://github.com/znatty22)
- [#1120](https://github.com/kids-first/kf-ui-data-tracker/pull/1120) - 💄 Change StudyNavBar Logs button to Events - [fec8e724](https://github.com/kids-first/kf-ui-data-tracker/commit/fec8e724b23ae34409c24bbdd7293586ebbe2797) by [gsantia](https://github.com/gsantia)
- [#1118](https://github.com/kids-first/kf-ui-data-tracker/pull/1118) - 🐛 Fix view only template missing function error on close - [93e76033](https://github.com/kids-first/kf-ui-data-tracker/commit …
=> 🏷 Release 0.23.2

src/releases/components/ReleaseDetail/Log.js, src/releases/components/ReleaseDetail/LogViewer.js
=> 🐛 Fix release log content cut off error

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#1127](https://github.com/kids-first/kf-ui-data-tracker/pull/1127) - 🐛 Fix release log content cut off error - [462d1349](https://github.com/kids-first/kf-ui-data-tracker/commit/462d1349ec10724a255d53ec1ddb5d178a1c9f04) by [XuTheBunny](https://github.com/XuTheBunny)
=> 🏷 Release 0.23.3

src/components/Header/Header.js
=> ♻️ Check if local stored organization belongs to user profile

CHANGELOG.md
- Emojis: ✨ x3
- Categories: Additions x3
- [#1139](https://github.com/kids-first/kf-ui-data-tracker/pull/1139) - ✨ Display when releases ended - [04138ca7](https://github.com/kids-first/kf-ui-data-tracker/commit/04138ca7fce6bf04dba698168608621ff2dded5f) by [gsantia](https://github.com/gsantia)
- [#1142](https://github.com/kids-first/kf-ui-data-tracker/pull/1142) - ✨ Download validation report from data review - [ac7f5e2b](https://github.com/kids-first/kf-ui-data-tracker/commit/ac7f5e2b8b7180b3c5b56ce54ae3279e2150c2a4) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1141](https://github.com/kids-first/kf-ui-data-tracker/pull/1141) - ✨ Add download button for admin template list - [f615a556](https://github.com/kids-first/kf-ui-data-tracker/commit/f615a55670f1c88097f34ce3206772c5f1dbd479) …
=> 🏷 Release 0.24.0

CHANGELOG.md
- Emojis: 💄 x1, ✨ x1
- Categories: Additions x1, Other Changes x1
- [#1152](https://github.com/kids-first/kf-ui-data-tracker/pull/1152) - 💄 Refactor UI margins and filter condition - [4756385c](https://github.com/kids-first/kf-ui-data-tracker/commit/4756385c5475f3bc7e145347947f9d3051255251) by [XuTheBunny](https://github.com/XuTheBunny)
- [#1148](https://github.com/kids-first/kf-ui-data-tracker/pull/1148) - ✨ Add new Study fields - [cba3bbad](https://github.com/kids-first/kf-ui-data-tracker/commit/cba3bbad27e380b96ce4912548b397b0f1dd95c6) by [gsantia](https://github.com/gsantia)
=> 🏷 Release 0.25.0

src/App.css, src/releases/components/ReleaseTable/ReleaseController.js, src/releases/components/ReleaseTable/ReleaseTable.js, src/releases/queries.js
=> ✨ Add filters for latest releases list

src/common/enums.js, src/components/TemplateList/TemplateList.js
4 file name pattern:
Closes #1149
=> ♻️ Use API provided file name for template downloads

src/forms/InviteForm.js
Closes https://github.com/kids-first/kf-api-study-creator/issues/812
=> ♻️ Automatically format user invite email address to lower case

src/App.css, src/admin/views/EventsView.js, src/common/enums.js, src/components/EventList/EventList.js, src/state/queries.js, src/views/LogsView.js
=> ✨ Show study id in the collaborator added logs
