.babelrc
package.json
yarn.lock

Running jest is not possible unless we make sure that all dependencies are running babel 7 or later.
This also adds missing presets for babel to `.babelrc`.

🔧 Ensure dependencies use babel 7

---

package.json
src/components/Badge/badge.css
src/components/FileAnnotation/FileEditor.js
src/components/FileAnnotation/SelectElement.js
src/components/FileAnnotation/fileannotation.css
src/components/FileList/FileElement.js
src/components/FileList/filelist.css
src/components/FileUpload/FileUploadTarget.js
src/components/FileUpload/file-upload.css
src/components/Login/Login.js
src/components/NavBar/NavBarButton.js
src/components/NavBar/navbar.css
src/components/StudyHeader/StudyHeader.jsx
src/components/StudyHeader/studyheader.css
src/components/StudyList/StudyCard.jsx
src/components/StudyList/StudyList.jsx
src/components/StudyList/studylist.css
src/views/AnnotationView.js
src/views/StudyFilesListView.js
yarn.lock

Use `uikit` version 0.5.0 and related layout style, and adjust existing styles accordingly. 
Future `uikit` component implementation would be in their separated pull requests. 
Closes #182

⬆️ Bump uikit version from 0.3.1 to 0.5.0 with related style adjustment

---

src/containers/NewTokenFormContainer.js
src/views/TokensListView.js

This updates the dev token list in the cache upon creating a new developer token. This was needed as tokens returned from the `allDevTokens` query were obfuscated, so the plaintext token returned in the mutation needed to be displayed for the user instead.
Fixes #204

♻️ Update dev token list from cache

---

src/components/Tokens/TokenList.js
src/state/mutations.js
src/views/TokensListView.js

Switches from using the `token` contents to the token's `name` in the `deleteDevToken` mutation and rewrites the `allDevTokens` query in the cache so that any tokens that have been created in the current page view do not get obfuscated unexpectedly.
Fixes #202 
Wait for #204 and kids-first/kf-api-study-creator#152 to merge

♻️ Delete token by name

---

__mocks__/kf-uikit.js
src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap

This replaces the `div` used for icon mocks with `svg` as `div` will cause warning when it is nested inside some html elements.
Will need to refresh all snapshots in open prs (again).

🐛 Fix icon mocks

---

src/components/CopyButton/CopyButton.css
src/components/CopyButton/CopyButton.js
src/components/CopyButton/CopyButton.test.js
src/components/CopyButton/__snapshots__/CopyButton.test.js.snap

Replace the old checkmark with green icon svg.
Replace the "Copied!" alert with tooltip underneath the checkmark.
On study header:
On file list:
Closes #200

♻️ Refactor copy button

---

__setups__/date.js
jest.config.js
src/components/FileList/__tests__/FileElement.test.js
src/components/FileList/__tests__/FileList.test.js
src/components/StudyHeader/StudyHeader.test.js
src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

This mocks `Date.now()` to return the same timestamp for all tests so that any instances of `TimeAgo` will return the same value over time.

✅ Global Date.now() mocking

---

src/components/StudyHeader/StudyHeader.jsx
src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap

Passing className twice was causing a linting error and may have
unintended styling effects.

🐛 Remove duplicate props

---

src/App.css

So the header logo can align with the main content
BEFORE:
AFTER:
Closes #240

💄 Align header to page content

---

src/components/StudyHeader/StudyHeader.css
src/components/StudyHeader/StudyHeader.jsx
src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap

**Previous look on large screen:**
The grid layout issue where study name and contact supposed to be at the same line on large screen
**Fixed look on large screen:**
**For medium and small screen:**
**Hide contacts for now (not connecting to any user profile data):**

💄Refactor study header style in grid layout

---

src/components/StudyHeader/StudyHeader.css
src/components/StudyHeader/StudyHeader.jsx
src/views/NavBarView.js

Display loading style on study header, maintaining the same component size for loading stage.
- This adjustment will prevent components from jumping up and down because of loading.
- This loading UI also fits all the responsive layout.

♻️ Refactor study header

---

src/Routes/index.js
src/components/FileDetail/FileDetail.js
src/components/FileDetail/__tests__/EditExistingFile.test.js
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/FileList/FileElement.js
src/components/FileList/FileList.js
src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/components/NavBar/NavBar.js
src/components/StudyList/StudyGrid.js
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
src/containers/StudySubscriptionContainer.js
src/containers/UploadContainer.js
src/modals/NewVersionModal/UploadStep.js
src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
src/views/NewDocumentView.js
src/views/StudyFilesListView.js
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

Renames all routes and references to the `file(s)` concept to use `document(s)` instead

♻️ Refactor upload verbiage

---

src/components/FileList/FileList.js
src/components/FileList/__tests__/FileList.test.js
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/components/FileList/filelist.css
src/components/Pagination/Pagination.js
src/components/Pagination/pagination.css
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

Update the styling of table pagination elements to more closely match that of the portal 
styling

💄 Refactor pagination styling

---

src/common/fileUtils.js
src/components/FileDetail/file-detail.css
src/forms/__snapshots__/NewDocumentForm.test.js.snap

Before:
After:
Closes #321 
Closes #322

🐛 Fix minor typo and style issue on file type and file description

---

src/common/fileUtils.js
src/forms/__snapshots__/NewDocumentForm.test.js.snap
src/modals/EditDocumentModal.js
src/modals/NewVersionModal/DescriptionStep.js
src/modals/NewVersionModal/NewVersionFlow.js
src/modals/NewVersionModal/UploadStep.js
src/modals/VersionInfoModal.js

Use semantic modal components to replace the local modal component.
Semantic components used:
- Grid
- Label
- Icon
- Button
- Modal
- Message
- Form
- Header
- Statistic
Closes #331

💄 Use Semantic for file edit / upload modals

---

src/components/CopyButton/CopyButton.js
src/components/FileActionButtons/FileActionButtons.js
src/components/FileList/FileElement.js
src/components/FileList/FileList.css
src/components/FileList/FileList.js
src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/containers/FileActionsContainer.js
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

This makes the FileList table selectable and allows user to click any where on the hovered row to go to that file.
Formats the buttons more consistently with the FileDetail view.
Makes button layout responsive by changing to horizontal fluid grouping on mobile.

💄 Usability improvements for FileList

---

src/App.css
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/StudyHeader/StudyHeader.js
src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap

Achieved HTML markup:
```
<div class="ui container">
<h1 class="ui header">Long Study Name</h1>
<h2 class="sub header study--header-sub">Short Study Name</h2>
<button />
</div>
```
Common case:
Long study name:
No short name:

💄 Semantic refactor for study header

---

src/views/StudyFilesListView.js

This replaces the `<Query />` component with the graphql HOC in the study file list
view as is consistent for views.
Closes #355

♻️ Replace Query component with HOC in study file list

---

__mocks__/kf-api-study-creator/mocks.js
__mocks__/kf-api-study-creator/responses/myProfile.json
src/components/FileDetail/__tests__/EditExistingFile.test.js
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/FileList/__tests__/FileList.test.js
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/forms/EditDocumentForm.js
src/forms/__snapshots__/EditDocumentForm.test.js.snap
src/modals/EditDocumentModal.js
src/state/client.js
src/state/clientSchema.js
src/state/queries.js
src/views/ProfileView.js

Augments the `UserNode` schema with client-side resolvers for `roles` and `groups` that read from the either the `accessToken` or `egoToken` in localStorage. Roles and groups can then be queried using the apollo-client `@client` directive
```
myProfile {
roles @client
groups @client 
}
```
---
🚧 🚧 🚧 🚧  🚧 🚧 🚧 🚧 🚧 🚧 
This is just a temporary solution as better options for this functionality could be: 
1) proxy every request for a user to auth0 for real time info
2) persist roles, groups in api and only update when user sends a new token
3) persist roles, groups in api and update periodically from auth0
Closes #312 
Closes #290

✨ Feature user roles client state

---

src/Routes/index.js
src/components/CavaticaProjectList/CavaticaProjectList.js
src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
src/components/CavaticaProjectList/index.js
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/Header/Header.js
src/state/fragments.js
src/state/mutations.js
src/state/queries.js
src/views/CavaticaProjectsView.js
src/views/index.js

Adds a view for admins to see what Cavatica projects are available, the studies linked to them, and an option to update projects by syncing with Cavatica.
Closes #411

✨ Add Cavatica Project list view

---

src/components/CavaticaProjectList/CavaticaProjectList.js
src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
src/forms/NewStudyForm.js

Date field cannot be set as empty strings to save to database, instead, should be set as null.
For projects which are linked to certain studies, we provide links to go to the documents page of that study.

🐛 Fix new study form date field and Cavatica project study link

---

src/containers/StudySubscriptionContainer.js

Doesn't render the study subscription list if the user does not belong to any studies or none are returned by the api.
Replaces the list with a message about not having access to studies yet.

🐛 Don't show studies in profile if the user has none

---

src/views/StudyListView.js

Since there's the StudyList including the add study button is hidden if there are no studies in the API, there is no way to add a new study starting from an empty state.
This shows a big button leading to the new study page for admins when they land on the study list with no studies.

✨ Add button to create first study for admins

---

src/forms/LinkProjectForm.js
src/modals/LinkProjectModal.js

This prevents the link projects modal from erroring when there are no projects available for linking.
It also adds a helpful message and disables the 'link' button in this scenario.
Fixes #443

🐛 Handle no projects

---

src/App.css
src/Routes/index.js
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/StudyNavBar/StudyNavBar.js
src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
src/forms/LinkProjectForm.js
src/modals/LinkProjectModal.js
src/views/CavaticaBixView.js
src/views/index.js

**Feature:**
- For ADMIN user, they can view a list of the Cavatica projects linked to the study they open
- For ADMIN user, they can c create/link/unlink projects (one at a time)
- For ADMIN user, they can see a warning when there is no delivery project or no analytic project
Add Cavatica tab under the study
Display the list of projects:
Warning for no delivery project or no analytic project:
Create project button pressed:
Link project button pressed:
Unlink button pressed:
Show empty page for not ADMIN user:
Show graphQL error:
Close #448

✨ Add Cavatica tab with Cavatica projects and create/link/unlink actions

---

src/components/CavaticaProjectList/CavaticaProjectItem.js
src/components/CavaticaProjectList/CavaticaProjectList.js
src/components/StudyInfo/StudyInfo.js
src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
src/state/queries.js
src/views/CavaticaBixView.js

- Filter out deleted projects from link project options dropdown.
- Show unlink project button when the project is deleted but still linked
- Show project name as the regular header when link is disbaled and hide link icon
- Add proptypes checking for CavaticaProjectItem component
- Minor fix on prop type error
Cavatica Project card on Study Basic Info page:
Before:
After:
Cavatica tab under the study:
Before:
After:
Link project modal:
Before:
After:
Cavatica project list page for ADMIN:
Before:
After:

♻️ Refactor project button and link rendering

---

src/views/NewDocumentView.js

This allows normal users to select a file type when creating a new document.
Normal users will still not be allowed to *change* the file type of an existing document, only new docs.

🐛 Allow selection of file type for normal users

---

src/App.css
src/Routes/index.js
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/StudyNavBar/StudyNavBar.js
src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
src/views/LogsView.js
src/views/index.js

**Feature:**
- For ADMIN user, they can view a list of event logs for the study
- For ADMIN user, they can filter event logs by event type
- Event logs refreshed every 30 seconds when on logs page
Add Logs tab under the study:
Display logs:
Applied filter:
Show empty page for not ADMIN user:
Show graphQL error:

✨ Add event logs tab view for ADMIN user with type filter and auto refresh

---

src/components/StudyList/StudyList.js
src/components/StudyList/__tests__/StudyList.test.js
src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap

- Make KfID for study searchable from the search box
- Add empty search stage for study grid view and table view
- Add snapshot test on study grid view and table view with the empty search state
Empty search stage for grid view and table view:
Before:
After:
Searching by kfId:
**UI reference:**
Study list page when the user doesn't  have any studies: (already implemented)
For ADMIN user:
For not ADMIN user:
Closes #474
Closes #470

♻️ Refactor study list search by adding empty state and make kfId searchable

---

src/components/TokenList/TokenList.js

Hides the copy button for masked tokens and moves the `CopyToClipboard` to wrap the Button rather than the other way around so that the entire button will trigger a copy.
**UI Changes:**
Before:
After
Fixes #480
Fixes #479

🐛 Hide copy button for masked tokens

---

src/common/dateUtils.js
src/components/AvatarTimeAgo/AvatarTimeAgo.js
src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
src/components/CavaticaProjectList/CavaticaProjectItem.js
src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
src/components/EventList/EventList.js
src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/components/FileList/FileElement.js
src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/components/StudyInfo/FileSimpleList.js
src/components/StudyInfo/StudyInfo.js
src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/components/TokenList/TokenList.js
src/components/TokenList/__snapshots__/TokenList.test.js.snap
src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

Update the `timeAgo` component hover title format to be `DD MMM YYYY`
e.g.: `12 Aug 2019` 
Before:
After:
Closes: #401

💄 Add user friendly time formats to TimeAgo on hover

---

src/components/VersionList/VersionItem.js

Adds a tooltip to the version list status item indicators for quick access to the version status
Closes #399

✨Feature version list item status tooltip

---

src/state/mutations.js

Had GraphQL error when trying to download a file or a version by calling signedUrl mutation:

🐛 Fix download mutation by removing the id

---

src/components/FileActionButtons/FileActionButtons.js
src/components/FileDetail/FileDetail.js
src/components/FileList/FileElement.js
src/components/FileList/FileList.js
src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/containers/FileActionsContainer.js
src/containers/FileDetailContainer.js
src/views/FileDetailView.js
src/views/StudyFilesListView.js
src/views/__tests__/StudyFilesListView.test.js
src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap

- Hide delete file button from non-admin users on file list page
- Hide delete file button from non-admin users on file detail page
**File list page:**  https://deploy-preview-515--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/documents
**Before:**
**After:**
**File detail page:**  https://deploy-preview-515--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/documents/SF_A9MMMZ6E
**Before:**
**After:**
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
Closes #351

💄 Hide delete file button from non-admin users on file list and file detail page

---

src/App.css
src/forms/StudyInfoForm/NewStudyForm.js
src/forms/StudyInfoForm/Steps/ExternalStep.js
src/forms/StudyInfoForm/Steps/InfoStep.js
src/forms/StudyInfoForm/Steps/LogisticsStep.js
src/views/StudyInfoView.js

- Default study info on editing for ADMIN and read-only for users
- Move the save button to each step
- Adjust the previous/next step button style
**Study info page:** https://deploy-preview-516--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/basic-info/info
**Before:**
ADMIN - read-only mode
ADMIN - editing mode
USER - read-only mode
**After:**
ADMIN - editing mode
USER - read-only mode
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
Closes #501

💄 Default study info on editing for ADMIN and read-only for regular users

---

netlify.toml
package.json
src/App.css
src/Routes/index.js
src/common/enums.js
src/components/Footer/Footer.js
src/components/Footer/__tests__/Footer.test.js
src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
src/components/Footer/index.js
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/documents/modals/UploadWizard/__tests__/UploadWizard.test.js
src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
src/views/__test__/__snapshots__/EventsView.test.js.snap
src/views/__test__/__snapshots__/LoginView.test.js.snap
src/views/__test__/__snapshots__/LogsView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap
src/views/__test__/__snapshots__/ProfileView.test.js.snap
src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
src/views/__test__/__snapshots__/TokenListView.test.js.snap

- Add UI version number and commit hash banner to footer
- Will add `Study Creator API` version later
- Have different look on production, development and local
**Before:**
**After:**
Local:
Development:
QA:
Production:
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
Closes #490

✨ Add UI version number banner to footer

---

src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/containers/StudySubscriptionContainer.js

- Fix study subscription table overflow columns in the user profile page
[**User profile page:**](https://deploy-preview-523--kf-ui-data-tracker.netlify.com/profile)
**Before:**
**After:**
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
Closes #517

🐛 Fix study subscription table overflow columns in the user profile page

---

src/App.css
src/documents/components/FileActionButtons/FileActionButtons.js
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/documents/components/FileList/FileElement.js
src/documents/components/FileList/FileList.js
src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/documents/components/ListFilterBar/ListFilterBar.js
src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
src/documents/views/StudyFilesListView.js
src/documents/views/__tests__/StudyFilesListView.test.js
src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap

- Add file list table header back
- Adjust the style of file filter to have proper margins
[Study document page](https://deploy-preview-522--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/documents)
**Before:**
**After:**
Full-size screen view:
Tablet screen view:
Mobile screen view: 
Closes #398

🐛 Add back study file list table header

---

netlify.toml

Updates the Study Creator API for QA/Netlify deployments to point to the kidsfirstdrc.org domain as the API is no longer being deployed to the kids-first.io domain.
N/A
N/A

👷 Update QA api to use kidsfirstdrc.org

---

src/App.css
src/common/enums.js
src/documents/components/FileDetail/SelectElement.js
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
src/documents/views/NewDocumentView.js
src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap

This feature will be used by both admin and regular users.
- Any users who uploaded a new file, they need to choose one file type (this field is required)
- Any users who want to edit an existing file, they can change the file type from the modal.
- Add file type description
- Adjust file type selection radio padding
- Update new document description and add contact email
**New file page:**
**Before:**
**After:**
**Edit file page:**
**Before:**
**After:**
Closes #488

💄 Add file type description

---

src/common/enums.js
src/views/__test__/__snapshots__/EventsView.test.js.snap
src/views/__test__/__snapshots__/LogsView.test.js.snap

Add icon mappings for the new event types to the [event enums](https://github.com/kids-first/kf-ui-data-tracker/blob/af89722e7dd26bdd689d85f068cf0cdc8d0a8702/src/common/enums.js#L79):
- `PR_STR`
- `PR_ERR`
- `PR_SUC`
- `BK_STR`
- `BK_ERR`
- `BK_SUC`
**[Events page](https://deploy-preview-555--kf-ui-data-tracker.netlify.com/events):**
**Full events type list:**
Closes #551

💄 Add icon mappings for new event types

---

__mocks__/kf-api-study-creator/mocks.js
__mocks__/kf-api-study-creator/responses/status.json
src/components/Footer/Footer.js
src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/state/queries.js
src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
src/views/__test__/__snapshots__/EventsView.test.js.snap
src/views/__test__/__snapshots__/LoginView.test.js.snap
src/views/__test__/__snapshots__/LogsView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap
src/views/__test__/__snapshots__/ProfileView.test.js.snap
src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
src/views/__test__/__snapshots__/TokenListView.test.js.snap

Add the version number of the study creator that results from the `status` query to the footer of the Data Tracker so that we may more easily determine currently deployed version.
**The footer on any page:**
**Before:**
**After:**
Closes #544

✨ Add study-creator-api version to footer

---

public/index.html

Adds the basic Hotjar tracking script into the head tag of the html document. This allows us to setup triggers for things such as session recording, heatmaps, and conversion funnels. The overall goal is to set these triggers based on event types fired from the Amplitude tracking event types so that associations can be made qualitative and quantitative findings to better triangulate areas of improvement for future testing and iteration. 
n/a
Checked that init call to Hotjar api was being called with http://localhost:3000/?hjVerifyInstall=1598076
| Browser             |  | 
| ------------------- | :----: | 
| Chrome (78.0.3904.108 )  |   ✅   |    
| Firefox (70.0.1 )|   ✅    |    
| Safari (13.0.3 )  |   ✅     |   
| IE Edge      |     ✅   |

📈Hotjar tracking script in head tag

---

package.json
src/Routes/index.js
src/components/StudyNavBar/StudyNavBar.js
src/components/StudyNavBar/__tests__/StudyNavBar.test.js
src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/documents/views/StudyFilesListView.js
src/views/CallbackView.js
src/views/CavaticaBixView.js
src/views/CavaticaProjectsView.js
src/views/EventsView.js
src/views/LoginView.js
src/views/LogoutView.js
src/views/LogsView.js
src/views/NewStudyView.js
src/views/ProfileView.js
src/views/StudyInfoView.js
src/views/StudyListView.js
src/views/TokensListView.js
src/views/__test__/TokenListView.test.js
src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__test__/__snapshots__/LoginView.test.js.snap
src/views/__test__/__snapshots__/LogsView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap
src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
yarn.lock

Provide descriptive page title when user navigates through the app. It's convenient for them to get to certain page when checking their browser visit history.
Add page title:
- `/` KF Data Tracker - Studies
- `/login` KF Data Tracker - Login
- `/logout` KF Data Tracker - Logout
- `/callback` KF Data Tracker - Forwarding
- `/profile` KF Data Tracker - Profile
- `/tokens` KF Data Tracker - Developer tokens
- `/events` KF Data Tracker - Events
- `/cavatica-projects` KF Data Tracker - Cavatica projects
- `/study/new-study` KF Data Tracker - New study
- `/study/{kfId}/basic-info` KF Data Tracker - Study info for {study name}
- `/study/{kfId}/documents` KF Data Tracker - Study documents for {study name}
- `/study/{kfId}/cavatica` KF Data Tracker - Study projects for {study name}
- …

✨ Add page titles to all views

---

src/components/StudyNavBar/StudyNavBar.js
src/components/StudyNavBar/__tests__/StudyNavBar.test.js
src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/views/StudyInfoView.js
src/views/__test__/StudyInfoView.test.js
src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__test__/__snapshots__/LogsView.test.js.snap
src/views/__test__/__snapshots__/StudyInfoView.test.js.snap

By removing the BETA role checking, all users (ADMIN or USER) can see the study info. 
- ADMIN can edit
- USER read-only
Team Leader (ADMIN), and investigators (USER) - To get study information by default. 
- Remove BETA user checking from study info page
- Remove "Beta" tag from study nav bar
**Study info page:**
**Before:**
For `BETA & ADMIN` user:
For `BETA & USER` user:
For `no BETA` user:
**After:**
For `ADMIN` user:
For `USER` user:

🔥 Remove BETA user checking from study info page

---

src/components/TokenList/TokenList.js
src/components/TokenList/__test__/TokenList.test.js
src/components/TokenList/__test__/__snapshots__/TokenList.test.js.snap
src/forms/NewTokenForm.js
src/views/TokensListView.js
src/views/__test__/__snapshots__/TokenListView.test.js.snap

- Allow ADMIN user to copy newly created token and hide all previous tokens.
**[Developer Tokens:](https://deploy-preview-561--kf-ui-data-tracker.netlify.com/tokens)**
**Before:**
**After:**

🐛 Allow admin user to copy newly created token

---

__mocks__/kf-api-study-creator/mocks.js
__mocks__/kf-api-study-creator/responses/allEvents_studyCreation.json
__mocks__/kf-api-study-creator/responses/allEvents_studyCreation_err.json
__mocks__/kf-api-study-creator/responses/allEvents_studyCreation_ing.json
__mocks__/kf-api-study-creator/responses/studyByKfId_event_err.json
src/App.css
src/common/enums.js
src/components/StudyHeader/StudyHeader.js
src/components/StudyHeader/__test__/StudyHeader.test.js
src/components/StudyHeader/__test__/__snapshots__/StudyHeader.test.js.snap
src/forms/StudyInfoForm/NewStudyForm.js
src/modals/CreatingStudyModal.js
src/modals/index.js
src/views/NavBarView.js
src/views/NewStudyView.js
src/views/__test__/NavBarView.test.js
src/views/__test__/NewStudyView.test.js
src/views/__test__/__snapshots__/NavBarView.test.js.snap
src/views/__test__/__snapshots__/NewStudyView.test.js.snap

To better communicate the next actions required from the administrator after creating a new study.
- What are the tasks processed for creating this study.
- When are they started
- When are they finished
- If they completed successfully or had any error
- If the study creation overall is done successfully or with any errors
- Additional (external) links to others sources that created along with the study creation.
Team Leader (ADMIN) - To quickly understand the status of study creation.
- Add new study creation status view
- Send user the study creation status view after they submit
**Forwarding page after submit a new study:**
**Before:**
**After:**
| Chrome (77)  | ✅ | ✅ | ✅ …

✨ Add new study creation status view

---

__mocks__/kf-api-study-creator/responses/status.json
src/Routes/index.js
src/components/Header/Header.js
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/state/queries.js
src/views/ConfigurationView.js
src/views/__tests__/ConfigurationView.test.js
src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
src/views/__tests__/__snapshots__/ConfigurationView.test.js.snap
src/views/__tests__/__snapshots__/EventsView.test.js.snap
src/views/__tests__/__snapshots__/LogsView.test.js.snap
src/views/__tests__/__snapshots__/NavBarView.test.js.snap
src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
src/views/__tests__/__snapshots__/ProfileView.test.js.snap
src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
src/views/__tests__/__snapshots__/TokenListView.test.js.snap
src/views/index.js

Adds a configuration view to evaluate the current Data Tracker settings.
**Page name here:** Configuration View
**After:**
Closes #issue-number

✨ Add configuration view

---

src/components/CavaticaProjectList/CavaticaProjectItem.js
src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectItem.test.js.snap
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/components/StudyInfo/FileCounts.js
src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
src/components/StudyList/StudyCard.js
src/components/StudyList/StudyGrid.js
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/documents/components/FileList/__tests__/FileList.test.js
src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
src/documents/components/ListFilterBar/ListFilterBar.js
src/documents/components/ListFilterBar/__test__/ListFilterBar.test.js
src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
src/documents/containers/UploadContainer.js
src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
src/views/__tests__/__snapshots__/StudyListView.test.js.snap

- Update file drag and drop box wording
- Replace 'Files' with 'Documents' in study table and document page
- Add margin between project study link and import file button
Closes #564
Closes #392
Closes #580

♻️ Refactor wording on document related pages

---

src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/components/StudyList/StudyList.js
src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
src/components/ToggleButtons/ToggleButtons.js
src/components/ToggleButtons/__tests__/ToggleButtons.test.js
src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
src/research/views/ResearchStudyListView.js
src/research/views/__tests__/ResearchStudyListView.test.js
src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
src/views/StudyListView.js
src/views/__tests__/StudyListView.test.js
src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
src/views/__tests__/__snapshots__/StudyListView.test.js.snap

- Add hash for delivery study list reflecting layout option
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/` -> List View
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/#list` ->  List View
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/#grid` -> Grid View
- Add hash for research study list reflecting layout option
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/research-studies` -> List View
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/research-studies#list` ->  List View
`https://deploy-preview-598--kf-ui-data-tracker.netlify.com/research-studies#grid` -> Grid View
No UI changes
| Chrome (_version_)  |   ✅   | …

✨ Add hash for study list reflecting layout option

---

src/Routes/index.js
src/state/auth.js
src/views/NotFoundView.js
src/views/__tests__/NotFoundView.test.js
src/views/__tests__/__snapshots__/NotFoundView.test.js.snap

- Display error description for auth error in alert
**When user goes back to callback page**
**When user is blocked from Auth0**
Closes #571

✨ Redirect user to error view when having auth0 error

---

__mocks__/kf-api-study-creator/mocks.js
__mocks__/kf-api-study-creator/responses/allUsers.json
src/Routes/index.js
src/admin/views/UsersView.js
src/admin/views/__tests__/EventsView.test.js
src/admin/views/__tests__/UsersView.test.js
src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
src/admin/views/__tests__/__snapshots__/UsersView.test.js.snap
src/admin/views/index.js
src/common/enums.js
src/components/Header/Header.js
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/research/views/__tests__/__snapshots__/NewResearchStudyView.test.js.snap
src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
src/state/queries.js
src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__tests__/__snapshots__/LogsView.test.js.snap
src/views/__tests__/__snapshots__/NavBarView.test.js.snap
src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
src/views/__tests__/__snapshots__/ProfileView.test.js.snap
src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
src/views/__tests__/__snapshots__/StudyListView.test.js.snap

Create an administrative view that allows admins to view all users that are registered in the data tracker.
The user list includes the following information:
- Username
- Picture
- Email
- Role
- Studies (in progress)
- Joined date
**[Users:](https://deploy-preview-599--kf-ui-data-tracker.netlify.com/users)**
Closes #590

✨ Add users view for admin

---

src/views/LoginView.js
src/views/__tests__/__snapshots__/LoginView.test.js.snap

Typo in redirect message.
- The redirect component had a typo, this fixes it. "Redirect" was misspelled.

🐛 Fixing redirect typo

---

src/Routes/index.js
src/admin/queries.js
src/admin/views/BucketsView.js
src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
src/admin/views/__tests__/__snapshots__/UsersView.test.js.snap
src/admin/views/index.js
src/components/BucketsList/BucketsList.js
src/components/BucketsList/__tests__/BucketList.test.js
src/components/BucketsList/__tests__/__snapshots__/BucketList.test.js.snap
src/components/BucketsList/index.js
src/components/Header/Header.js
src/components/Header/__tests__/__snapshots__/Header.test.js.snap
src/components/index.js
src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
src/research/views/__tests__/__snapshots__/NewResearchStudyView.test.js.snap
src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
src/views/__tests__/BucketsView.test.js
src/views/__tests__/__snapshots__/BucketsView.test.js.snap
src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
src/views/__tests__/__snapshots__/LogsView.test.js.snap
src/views/__tests__/__snapshots__/NavBarView.test.js.snap
src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
src/views/__tests__/__snapshots__/ProfileView.test.js.snap
src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
src/views/__tests__/__snapshots__/StudyListView.test.js.snap

Adds a bucket view for admins to evaluate what study buckets are available.
**Page name here:** Buckets
**After:**
Closes #issue-number

✨ Add buckets view

---

src/common/enums.js
src/components/EventList/EventList.js
src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap

✨ Add icon enums for add/remove collaborators event
✨ Add link access to the study/file/version kfId in event description 
**Study logs page:**
**Before:**
**After:**
**Admin event list page:**
**Before:**
**After:**
Closes #525

✨ Hyperlink IDs in event logs feature 

---

src/containers/StudySubscriptionContainer.js

The new collaborators field on the user response was causing the StudyList in the user profile to break. This adds the collaborators field to the exclude list on the profile.

🐛 Hide collaborators column

---

src/views/CollaboratorsView.js

- Only renders the add collaborator button if the user has the `add_collaborator` permission.
- Only shows admin actions on collaborators if the user has the `remove_collaborator` permission.
Closes #658

🔒 Check for permissions on collaborator tab

---

src/routes/index.js

Protects events view by checking that the user have the `view_event` permission before rendering.
Closes #652

🔒 Protect events

---

src/routes/index.js

Only show the configuration view for users with the `view_settings` permission.
Closes #654

🔒 Protect configuration view

---

src/components/StudyList/ColumnSelector.js
src/components/StudyList/StudyList.js
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/StudyTable.test.js
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/containers/StudySubscriptionContainer.js

Allows the user to change what columns are displayed in the study list table.
Defaults to `Name`, `KF ID`, `Version`, and `Actions`. `Name` is always displayed on the first column and `Actions` on the last.
The user's column selection is persisted to localStorage so that it is reloaded next time the app refreshes. A `version` key in the stored item is kept so that the setting may be updated if the schema ever changes which could cause an error otherwise.
Closes #682

✨ Select study list columns

---

cypress/integration/studies/add_study.spec.js
cypress/integration/studies/study_list.spec.js
cypress/integration/studies/study_statuses.spec.js
src/components/StudyList/Name.js
src/components/StudyList/StudyList.js
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap

Saves the state of the `show only my studies` checkbox to localstorage so that it is restored when the page or view is reloaded.
closes #681

✨ Persist show only my studies state

---

CHANGELOG.md
package.json

Add study status columns.
Feature Emojis: ✨x4 🐛x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/feature) x4 [design](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/design) x2 [bug](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/bug) x1 [component](https://api.github.com/repos/kids-first/kf-ui-data-tracker/labels/component) x1
- (#699) ✨ Add ingestion status and phenotype status to study table - @XuTheBunny
- (#698) 🐛 Fix version sorting - @dankolbman
- (#697) ✨ Persist show only my studies state - @dankolbman
- (#685) ✨ Add sequencing status selector - @dankolbman
- (#696) ✨ Full width study table toggle - @dankolbman

🏷 Release 0.13.0

---

cypress/integration/studyInfo/collaborators.spec.js
src/admin/components/UserList/UserItem.js
src/common/notificationUtils.js
src/components/AvatarTimeAgo/AvatarTimeAgo.js
src/components/CollaboratorsList/CollaboratorItem.js
src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap
src/components/StudyList/Name.js
src/forms/AddCollaboratorForm.js

♻️ Render study collaborator with user full name display in study list
♻️ Render collaborator list with user full name in collaborator tab
♻️ Render collaborator list with user full name in add collaborator modal
♻️ Render user list with user full name in admin user page

✨ Display collaborators full name

---

src/routes/TrackedRoute.js

`LogOnMount` would not fire events when mounting so this will manually trigger events through `logEvent` whenever a route is rendered.

🐛 Manually log page views

---

src/analyticsTracking/AmplitudeUser.js

```const profileProps = this.profile && this.getProfileProps(this.profile);```
Handle the situation when `profileProps` is null before setting Amplitude properties.
```
profileProps.groups && identify.set('groups', profileProps.groups);
profileProps.studies && identify.set('studies', profileProps.studies);
profileProps.dateJoined && identify.set('dateJoined', profileProps.dateJoined);
```

🐛 Handle no user profile case for setting amplitude properties

---

src/analyticsTracking/AmplitudeUser.js

Check for values in profile retrieved from localstorage before attempting to set them in the analytics user.

🐛 Defensively check for localStore attributes

---

src/views/InviteView.js

Sends the url including the referral token to Auth0 so that the user may log in or signup before exchanging a referral token.

🐛 Include token when logging users into invite view

---

src/views/InviteView.js

Checks that both the access token is in localstorage and that the expiration time is valid before deciding if to send the user to log in before exchanging a token.

🐛 Check expiration time for token validation

---

CHANGELOG.md

Fix errors when data is not present.
- Emojis: 🐛 x2, ✨ x1, ⬆️ x1
- Categories: Fixes x2, Additions x1, Ops x1
- [#735](https://github.com/kids-first/kf-ui-data-tracker/pull/735) - 🐛 Fix study header and document loading error - [859c03fa](https://github.com/kids-first/kf-ui-data-tracker/commit/859c03fab304d82b74df1038b78d8d302d44e4af) by [XuTheBunny](https://github.com/XuTheBunny)
- [#734](https://github.com/kids-first/kf-ui-data-tracker/pull/734) - 🐛 Fix unique key error on study and configuration tables - [55c0b239](https://github.com/kids-first/kf-ui-data-tracker/commit/55c0b23957433d26f3032552b0c54e43d5366b6b) by [XuTheBunny](https://github.com/XuTheBunny)
- [#733](https://github.com/kids-first/kf-ui-data-tracker/pull/733) - ✨ Allow slack channel to be updated - …

🏷 Release 0.14.1

---

cypress/integration/documents/document_list.spec.js
src/App.css
src/documents/components/ListFilterBar/BatchActionBar.js
src/documents/components/ListFilterBar/BatchActions.js
src/documents/components/ListFilterBar/ListFilterBar.js
src/documents/components/helpers/BaseHelper.js
src/documents/views/StudyFilesListView.js

Disable batch action buttons when no files are selected:
Enable batch action buttons when one or more files are selected:
Only Admin user can see the delete button:
Closes #741

♻️ Always display bulk document actions

---

src/admin/views/ConfigurationView.js
src/state/queries.js

Call the following queries to get the fields for Status query:
```
query features {
__type(name: "Features") {
name
fields {
name
}
}
}
query settings {
__type(name: "Settings") {
name
fields {
name
}
}
}
```
Status query:
```
query Status {
status {
name
version
commit
features {
...FeaturesFields
}
settings {
...SettingsFields
}
queues
jobs {
edges {
node {
id
name
active
failing
lastRun
lastError
createdOn
enqueuedAt
}
}
}
}
}
${FEATURES_FIELDS}
${SETTINGS_FIELDS}
```
Closes #742

✨ Add missing fields to configuration page 

---

cypress/integration/documents/document_detail.spec.js
cypress/integration/documents/document_list.spec.js
src/documents/components/FileDetail/FileDetail.js
src/documents/components/FileDetail/FileTags.js
src/documents/components/FileList/FileElement.js
src/documents/components/FileList/FileList.js
src/documents/components/ListFilterBar/ListFilterBar.js
src/documents/views/FileDetailView.js
src/documents/views/StudyFilesListView.js

1. Remove default tag suggestions from the options
2. Provide used tags in current study as select options (except for the the ones are already used in current document)
3. Can filter by current used tags in this study
Closes #758

🔥 Remove default document tag options

---

cypress/integration/studyInfo/cavatica.spec.js
src/common/enums.js
src/forms/EditProjectForm.js
src/modals/CreatingStudyModal.js
src/modals/EditProjectModal.js
src/views/CavaticaBixView.js

3 level dropdown to select workflow type, method and sample type
Select workflow type to enable method, select method to enable sample type
All 3 dropdown has to have value to enable to the confirm checkbox (and copy to clipboard popup)
Add study kfID to Cavatica project name preview and copy to clipboard
Has to check the confirm checkbox to enable the creation of Cavatica project
In query, the workflow type are sent without study kfID
Closes #749

✨ Set Cavatica workflow type selection with type, method and sample type

---

src/components/StudyList/StudyList.js
src/components/StudyList/StudyTable.js
src/views/StudyListView.js

Updates the study list view to use `cache-and-network` which will immediately serve studies from the cache but will also make a request for the latest data.
This will speed up the render time when a user returns to the study list page after viewing another page in-between.

♻️ Update study list to use cache-and-network policy

---

CHANGELOG.md
release_maker_cfg.json

- Emojis: 📈 x1, ♻️ x2, 🐛 x2, ✨ x4, 💄 x1, 🔥 x3
- Categories: Additions x5, Other Changes x3, Fixes x2, Removals x3
- [#781](https://github.com/kids-first/kf-ui-data-tracker/pull/781) - 📈 Add tracking to document uploads - [98e63096](https://github.com/kids-first/kf-ui-data-tracker/commit/98e63096cad6751cd1812914f0f605add7704c1a) by [dankolbman](https://github.com/dankolbman)
- [#779](https://github.com/kids-first/kf-ui-data-tracker/pull/779) - ♻️ Update study list to use cache-and-network policy - [09c82315](https://github.com/kids-first/kf-ui-data-tracker/commit/09c82315557da9b436a931d8522503643969f93b) by [dankolbman](https://github.com/dankolbman)
- [#778](https://github.com/kids-first/kf-ui-data-tracker/pull/778) - 🐛 Fix study table sorting error on expected samples column - …

🏷 Release 0.15.0

---

src/forms/AddCollaboratorForm.js

Adds the user's email to the user drop down on collaborator invite modals to allow differentiation between similarly named users.
Closes #808

💄 Add user's email to user drop down

---

src/documents/modals/EditDocumentModal.js

When user click on the save button, we want to check if there are any changes being made first, if has changes then we call the updateFile mutation. This will eliminate the case that nothing is updated, and a update file event is still created.
Ref: https://github.com/kids-first/kf-api-study-creator/issues/435

♻️ Only call updateFile mutation from edit file modal if has changes

---

src/documents/forms/EditDocumentForm.js
src/documents/forms/ExistingDocsMessage.js
src/documents/forms/__tests__/ValidationFunction.test.js
src/documents/forms/validate.js

Remove the warning when document title is similar to the uploaded file name.
Before:
Now:

🔥 Remove new document title and file name similarity checking

---

src/documents/components/FileDetail/AnalysisSummary.js
src/documents/components/FileDetail/FileDetail.js
src/documents/queries.js

Adds a document structure summary section to the document detail view to outline the contents of files.

✨ Add analysis summary to file detail

---

src/admin/views/ConfigurationView.js

Doesn't render the status tables until the settings and features queries have resolved so that the fragments for the status query may be built.

🐛 Wait for queries before building fragments

---

src/documents/views/UploadView.js

Fixes the 'Upload a Different File' button by passing the correct study object into the UploadBar component.

🐛 Pass correct study object to upload bar

---

src/documents/components/FileDetail/FileDetail.js

Moves the document summary section below the document version section of the file detail view.
Closes #859

🎨 Move summary section below versions

---

.circleci/config.yml

Bumps the node image on CircleCI to allow use of the netlify-cli package.

⬆️  Bump node image version

---

src/documents/components/FileDetail/AnalysisSummary.js
src/documents/components/FileDetail/FileDetail.js
src/documents/forms/NewDocumentForm.js
src/documents/views/FileDetailView.js
src/documents/views/UploadView.js

When considering "go back", we want user to be redirected back to the file list page from file detail page after they delete the file. This will avoid the case when user are guided from file upload page directly to file detail page. 
`GET_STUDY_BY_ID` query take ID type `id` as variable instead of `kfId`.
Closes #865

🐛 Fix delete file from file detail page refetch query variable

---

CHANGELOG.md

- Emojis: 🐛 x1, ⬆️ x1, 🔥 x1
- Categories: Fixes x1, Ops x1, Removals x1
- [#884](https://github.com/kids-first/kf-ui-data-tracker/pull/884) - 🐛 Fix delete file from file detail page refetch query variable - [b72d990b](https://github.com/kids-first/kf-ui-data-tracker/commit/b72d990b456060b66e648f71a2dfd58e63c8a4d6) by [XuTheBunny](https://github.com/XuTheBunny)
- [#885](https://github.com/kids-first/kf-ui-data-tracker/pull/885) - ⬆️  Bump node image version - [52583221](https://github.com/kids-first/kf-ui-data-tracker/commit/52583221139c1b8c6ea38fa3176c96a3e8ad8607) by [dankolbman](https://github.com/dankolbman)
- [#882](https://github.com/kids-first/kf-ui-data-tracker/pull/882) - 🔥 Remove obsolete new document view and /new-document route - …

🏷 Release 0.17.1

---

netlify.toml
src/App.js
src/common/globals.js

Redirects the application to the desired host if given. This allows us to funnel multiple deployments at different domains to one central location.

🔧 Redirect host

---

netlify.toml

Adds an Amplitude key for our dev/QA data source to the qa and dev builds on netlify. The production amplitude key will get inherited from the Netlify UI on production builds.

🔧 Add dev/QA amplitude key to netlify builds

---

__mocks__/kf-api-study-creator/mocks.js
src/App.css
src/documents/components/FileDetail/FileDetail.js
src/documents/components/FileDetail/Timelines.js
src/documents/modals/EditDocumentModal.js
src/documents/modals/NewVersionModal/NewVersionFlow.js
src/documents/views/FileDetailView.js
src/state/queries.js

**FEATURES:**
- Get 20 most recent events for specific document for timelines
- Strip off the file ID when displayed as timeline on file detail page
- Timeline component has empty, error and loading stage
- Timeline auto refresh on document updates and new versions
Closes #866

✨ Add document recent events as timeline to document detail page

---

src/App.css
src/releases/routes.js
src/releases/views/HomeView.js
src/releases/views/ReleaseDetailView.js
src/releases/views/ServicesListView.js

Make the route for new release to be history/new-release, so that is shows under the latest releases tab
Update release detail view error message
Note 20 most releases / services in title

💄 UI updates around releases and services page

---

.circleci/config.yml
netlify.toml

This sets the netlify production environment to redirect to the qa url instead of the master. This will allow us to access qa api and interface through https://kf-ui-data-tracker-qa.kidsfirstdrc.org.

👷‍♂️ Use netlify production as qa

---

cypress/integration/studies/study_list.spec.js
src/App.css
src/common/globals.js
src/components/StudyList/ActionButtons.js
src/components/StudyList/Name.js
src/components/StudyList/StudyList.js
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/StudyTable.test.js
src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap

**FEATURES:**
- Allow users to favorite studies
- Save favorite studies data to local storage
- Splitting the studies list into "favorite studies" and "all studies"
- Search study function and "show only my study" function only apply to all studies table
- Change columns function and full width function apply to both "favorite studies" and "all studies" table
- Both "favorite studies" and "all studies" table support column sorting
- Have empty messages for no favorite studies or no studies matching the search in "all studies" table
- Add pagination for "favorite studies" and "all studies" table with default 10 studies per page
Closes #921

✨ Allow users to favorite studies and display ‘favorite studies’ list

---

.circleci/config.yml

`.test-result` only has contents from the docker compose command and doesn't contain anything after running `docker cp` so is not necessary.

🐛 Don't return exit code for copying artifacts

---

src/releases/components/ReleaseTable/Name.js
src/releases/components/ReleaseTable/ReleaseTable.js

Makes the entire cell clickable to navigate to a specific release and makes the table selectable.

💄 Increase hit area for releases

---

src/releases/forms/NewReleaseForm.js
src/releases/queries.js
src/releases/views/NewReleaseView.js

Only shows enabled services to choose from when creating a new release.

💄 Only show enabled services in new release form

---

src/components/Footer/Footer.js

- When  study-creator version number string is 'LOCAL' disable the link
- Version number string for study-creator in footer contains "v", it needs to be removed from the url.
Closes #953

🐛 Fix footer backend version link

---

src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
src/components/Header/DevHeader.js
src/state/queries.js

The status query is now only used to display basic version info in the footer of the page. Our configuration page now uses a dynamic query that is generated and executed based on what fields exist on the status schema.
This fixes current issue of having a field moved on the status schema and will avoid any future issues where the settings and feature schema may change on the status model.

🔥 Remove unused status fields

---

src/admin/views/CavaticaProjectsView.js
src/state/fragments.js

Remove the soon to be deprecated `roles` from user queries. This field is not currently used in the UI or the backend.

🔥 Remove roles from user fragment

---

cypress/integration/studies/study_list.spec.js
src/App.css
src/components/StudyList/Name.js
src/components/StudyList/StudyList.js
src/components/StudyList/StudyTable.js
src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
src/forms/StudyInfoForm/NewStudyForm.js
src/views/StudyInfoView.js

✨ Add toggle full width button on Favorite Studies section
💄 Move search bar to top and hide fav studies on search
Closes #1007 
💄 Move fav study button to its own column
💄 Make study name and investigators badge overflow wrap
✨ Allow show less/more study investigators badges 
Closes #1006
Closes #1008 
💄 Add loading stage for study info page updates
Closes #1009

💄 Refactor study list sizing and add favorite studies search

---

src/documents/components/FileDetail/FileDetail.js
src/documents/components/FileDetail/FileTags.js
src/documents/components/FileFolder/FileFolder.js
src/documents/components/FileFolder/FileSimpleElement.js
src/documents/components/FileList/FileElement.js
src/documents/components/ReviewFiles/ReviewFileElement.js

**Hide overflow file name and display full name in popup**
1. In document folder table
2. In document list table
3. In review add document table
**Display limited number of tags and show the rest in popup **
Closes #1051
Closes #1050

💄 Adjust document table file name and tags display

---

src/components/CollaboratorsList/CollaboratorsList.js

When a study has more than 1 collaborators, this error shows.
Fixed by making a copy of user array before sorting method.
`users.sort()` -> `[...users].sort()`

🐛 Fix study collaborator list display error

---

src/modals/AddCollaboratorModal.js
src/modals/InviteModal.js

Uses the active organization when sending email invites from the invite modal or the add collaborator modal.
Depends on #1044

♻️ Attach organization to invites

---

src/releases/components/StudyTable/StudyTable.js
src/state/queries.js

Error:
`Variable \"eventType\" of type \"String\" used in position expecting type \"EventEventType\".`
Fixed by:
In `allEvents` query input change `$eventType: String` to `$eventType: EventEventType`

🐛 Fix allEvents query input event type

---

.circleci/config.yml

The static site orb is trailing on the awscli setup script causing it to fail installation. This replaces the orb with circle maintained aws-s3.

♻️ Replace static site orb with s3 orb

---

src/documents/components/FileActionButtons/FileActionButtons.js
src/documents/components/FileUpload/FileUploadTarget.js
src/documents/components/FileUpload/__test__/__snapshots__/FileUploadTarget.test.js.snap
src/documents/components/ListFilterBar/BatchActions.js
src/documents/views/StudyFilesListView.js

💄 Toggle between no files message and upload drag and drop box
Closes #1110
Closes #1109
♻️ Force reload study document page after delete file to regroup folders
Closes #1108

♻️ Refactor study document tab layout and refetch

---

src/components/StudyNavBar/StudyNavBar.js
src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
src/routes/index.js

Closes #1094 . Changes the StudyNavBar Logs button to say Events and updates the route name from `logs` to `events`.
This button used to say Logs

💄Change StudyNavBar Logs button to Events

---

src/common/enums.js
src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
src/documents/components/UploadSteps/ChooseTypeStep.js
src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap

Bring back the old general file types and add additional useful general types:
When there are templates available for a study

✨ Better general file types

---

src/common/notificationUtils.js
src/components/StudyInfo/__test__/__snapshots__/ProgressBar.test.js.snap
src/forms/StudyInfoForm/NewStudyForm.js
src/forms/StudyInfoForm/Steps/InfoStep.js
src/state/fragments.js

Closes #1145 . Adds new Study fields (`short_code`, `program`, and `domain`) from the [backend](https://github.com/kids-first/kf-api-study-creator/issues/788) to the StudyForm. These fields are all required and are added to both Study creation and editing.
`short_code` and `program` are free text fields, while `domain` is an enum so it is handled with a select dropdown menu.

✨ Add new Study fields

---

src/admin/views/EventsView.js
src/admin/views/UsersView.js
src/components/ReleaseList/ReleaseList.js
src/forms/StudyInfoForm/Steps/InfoStep.js

💄 Fix release table footer length
💄 Make release date inline on study release tab
💄 Add margins to admin events filter dropdown
✨ Add NOT condition on admin user list filter
Closes #1151

💄 Refactor UI margins and filter condition

---

src/admin/views/EventsView.js

Passing empty string as event type cause graphql error.
Fix by passing `null` value instead of empty string.
Closes #1158

🐛 Fix event type filter from admin events page
